#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr15 import write

write("de", [
"Genau nach Osten, zwölf Kilometer entfernt — der massige, flach abgeschnittene Berg am Horizont.",
"der Landarzt, der herausfand, wie sich Gletscher bewegen",
"der Hof, der bergauf umgezogen ist",
"ein Wasserfall auf porösem Lavagestein, dessen Namen nie jemand aufgeschrieben hat",
"ein See, gespeist von einem Fluss, ohne oberirdischen Abfluss",
"ein 4.000 Jahre altes Lavafeld aus vier Ljósufjöll-Kratern",
"der Damm von 2004 und was er mit einem Fjord angestellt hat",
"das Eis hat eine ganze Landschaft abgetragen und das beste Stück stehen lassen",
"Meeresmuscheln, versiegelt unter Lava, datiert auf rund 1,1 Millionen Jahre",
"die Brauerei, benannt nach dem Dichter und Raufbold der Egils saga",
"die zwei Berserker und die Straße, für die sie mit einem Bad bezahlt wurden",
"Eyrbyggja saga, Kapitel 11: Der Berg öffnet sich und die Toten werden hineingebeten",
"Þrælaskriður aus der Eyrbyggja saga — die Sklavenhänge",
"Geirríður aus der Eyrbyggja saga, beschuldigt, nachts zu reiten",
"die drei Wünsche, erstmals 1955 aufgeschrieben",
"die Anklage als kveldriða, beantwortet vor Gericht statt auf dem Scheiterhaufen",
"Bachforellen von drei bis sechs Pfund und Saiblinge am Lavarand",
"fünfzigtausend Tonnen Hering, zweimal in sechs Wochen",
"die Seehunde mit festen Bürozeiten",
"der Siedler, benannt nach der Richtung, in die er nicht wollte",
"die Kirche von 1856–58, die letzte ihrer Art, die noch steht",
"Þórólfurs heiliger Berg: Niemand durfte ihn ungewaschen ansehen",
"die Brauerei, benannt nach einem Saga-Dichter",
"das Thing, das schon vor dem Alþingi tagte",
"eine Hexerei-Anklage, die vor Gericht endete und nicht im Feuer",
"der Pfeilspitzen-Berg aus *Game of Thrones*",
"🍽️ Essen & Trinken",
"hákarl — und warum der Hai erst richtig verrotten muss, bevor er sicher ist",
"🕰️ Geschichte",
"der eine Wasserfall in einem Land voller benannter Gewässer, der nie einen Namen bekam",
"der Strudel, den ein Bauernjunge bemerkte und dem nie jemand nachging",
"🔤 Sprache & Namen",
"„Flussfall“ — Isländisch für „wir haben uns keine Mühe gegeben“",
])

write("fr", [
"Plein est, à douze kilomètres — la grande montagne au sommet plat sur l'horizon.",
"le médecin de campagne qui a compris comment les glaciers se déplacent",
"la ferme qui a déménagé vers le haut",
"une cascade sur de la lave poreuse, dont personne n'a jamais noté le nom",
"un lac alimenté par une rivière et sans aucun exutoire en surface",
"un champ de lave vieux de 4 000 ans, issu de quatre cônes du Ljósufjöll",
"la chaussée de 2004 et ce qu'elle a fait à un fjord",
"la glace a soustrait tout un paysage et laissé debout le meilleur morceau",
"des coquillages marins scellés sous une lave datée d'environ 1,1 million d'années",
"la brasserie qui porte le nom du poète bagarreur de la Egils saga",
"les deux berserkers et la route qu'on leur a payée en bain",
"Eyrbyggja saga, chapitre 11 : la montagne s'ouvre et les morts y sont accueillis",
"les Þrælaskriður de la Eyrbyggja saga — les Éboulis des Esclaves",
"Geirríður de la Eyrbyggja saga, accusée de chevaucher la nuit",
"les trois vœux, couchés par écrit pour la première fois en 1955",
"l'accusation de kveldriða, réglée au tribunal plutôt qu'au bûcher",
"des truites de trois à six livres, et des ombles le long de la lave",
"cinquante mille tonnes de hareng, deux fois en six semaines",
"les phoques qui respectent les heures de bureau",
"le colon nommé d'après la direction qu'il refusait de prendre",
"l'église de 1856–58, la dernière de son espèce encore debout",
"la montagne sacrée de Þórólfur : interdit de la regarder sans s'être lavé",
"la brasserie qui porte le nom d'un poète des sagas",
"l'assemblée qui siégeait avant même l'Alþingi",
"une accusation de sorcellerie qui a fini au tribunal, pas au bûcher",
"la montagne en pointe de flèche de *Game of Thrones*",
"🍽️ Manger & boire",
"le hákarl, et pourquoi le requin doit d'abord pourrir comme il faut",
"🕰️ Histoire",
"la seule cascade, dans un pays où toute eau a un nom, à n'en avoir jamais reçu",
"le tourbillon qu'un fils de fermier a remarqué et que personne n'a suivi",
"🔤 Langue & noms",
"« chute de la rivière » — de l'islandais pour « on ne s'est pas foulé »",
])

write("es", [
"Justo al este, a doce kilómetros — la enorme montaña de cima plana en el horizonte.",
"el médico rural que descubrió cómo se mueven los glaciares",
"la granja que se mudó ladera arriba",
"una cascada sobre lava porosa cuyo nombre nadie llegó a anotar",
"un lago alimentado por un río y sin salida alguna en la superficie",
"un campo de lava de 4.000 años surgido de cuatro conos del Ljósufjöll",
"el terraplén de 2004 y lo que le hizo a un fiordo",
"el hielo restó un paisaje entero y dejó en pie lo mejor",
"conchas marinas selladas bajo lava datada en unos 1,1 millones de años",
"la cervecería que lleva el nombre del poeta pendenciero de la Egils saga",
"los dos berserkers y el camino que les pagaron con un baño",
"Eyrbyggja saga, capítulo 11: la montaña se abre y a los muertos se les da la bienvenida",
"los Þrælaskriður de la Eyrbyggja saga — los Derrubios de los Esclavos",
"Geirríður de la Eyrbyggja saga, acusada de cabalgar de noche",
"los tres deseos, puestos por escrito por primera vez en 1955",
"la acusación de kveldriða, resuelta en un tribunal y no en una hoguera",
"truchas de tres a seis libras y sávalos árticos junto al borde de lava",
"cincuenta mil toneladas de arenque, dos veces en seis semanas",
"las focas que cumplen horario de oficina",
"el colono llamado por la dirección a la que no quiso ir",
"la iglesia de 1856–58, la última de su tipo en pie",
"la montaña sagrada de Þórólfur: nadie podía mirarla sin lavarse",
"la cervecería que lleva el nombre de un poeta de las sagas",
"la asamblea que se reunía antes de que existiera el Alþingi",
"una acusación de brujería que acabó en juicio y no en fuego",
"la montaña con forma de punta de flecha de *Game of Thrones*",
"🍽️ Comida y bebida",
"el hákarl, y por qué el tiburón tiene que pudrirse bien antes de ser seguro",
"🕰️ Historia",
"la única cascada, en un país donde toda el agua tiene nombre, que nunca recibió uno",
"el remolino que vio un hijo de granjeros y que nadie llegó a investigar",
"🔤 Lengua y nombres",
"«cascada del río» — islandés para «no nos molestamos»",
])

write("it", [
"Esatto est, a dodici chilometri — la grande montagna dalla cima piatta all'orizzonte.",
"il medico di campagna che capì come si muovono i ghiacciai",
"la fattoria che ha traslocato più in alto",
"una cascata su lava porosa di cui nessuno ha mai scritto il nome",
"un lago alimentato da un fiume e senza alcuna uscita in superficie",
"un campo lavico di 4.000 anni uscito da quattro coni del Ljósufjöll",
"la strada rialzata del 2004 e quel che ha fatto a un fiordo",
"il ghiaccio ha sottratto un intero paesaggio e lasciato in piedi il pezzo migliore",
"conchiglie marine sigillate sotto lava datata a circa 1,1 milioni di anni",
"il birrificio intitolato al poeta attaccabrighe della Egils saga",
"i due berserker e la strada che si fecero pagare con un bagno",
"Eyrbyggja saga, capitolo 11: la montagna si apre e i morti vi sono accolti",
"gli Þrælaskriður della Eyrbyggja saga — le Frane degli Schiavi",
"Geirríður della Eyrbyggja saga, accusata di cavalcare di notte",
"i tre desideri, messi per iscritto per la prima volta nel 1955",
"l'accusa di kveldriða, risolta in tribunale invece che sul rogo",
"trote fario da tre a sei libbre e salmerini lungo il bordo della lava",
"cinquantamila tonnellate di aringhe, due volte in sei settimane",
"le foche che rispettano l'orario d'ufficio",
"il colono chiamato con il nome della direzione in cui non volle andare",
"la chiesa del 1856–58, l'ultima del suo genere ancora in piedi",
"la montagna sacra di Þórólfur: nessuno poteva guardarla senza essersi lavato",
"il birrificio intitolato a un poeta delle saghe",
"l'assemblea che si riuniva prima ancora che esistesse l'Alþingi",
"un'accusa di stregoneria finita in tribunale, non sul rogo",
"la montagna a punta di freccia di *Game of Thrones*",
"🍽️ Cibo e bevande",
"lo hákarl, e perché lo squalo deve marcire come si deve prima di essere sicuro",
"🕰️ Storia",
"l'unica cascata, in un paese dove ogni acqua ha un nome, a non averne mai avuto uno",
"il vortice che notò un figlio di contadini e che nessuno andò mai a verificare",
"🔤 Lingua e nomi",
"«cascata del fiume» — islandese per «non ci siamo sforzati»",
])

write("nl", [
"Pal naar het oosten, twaalf kilometer verderop — de massieve berg met de vlakke top aan de horizon.",
"de plattelandsdokter die uitvond hoe gletsjers bewegen",
"de boerderij die de heuvel op verhuisde",
"een waterval op poreus lava waarvan niemand de naam heeft opgeschreven",
"een meer dat door een rivier gevoed wordt en bovengronds nergens uitstroomt",
"een 4.000 jaar oud lavaveld uit vier kegels van de Ljósufjöll",
"de dam uit 2004 en wat die met een fjord deed",
"het ijs trok een heel landschap af en liet het mooiste stuk staan",
"zeeschelpen verzegeld onder lava van ongeveer 1,1 miljoen jaar oud",
"de brouwerij vernoemd naar de dichter en vechtersbaas uit de Egils saga",
"de twee berserkers en de weg waarvoor ze met een bad betaald werden",
"Eyrbyggja saga, hoofdstuk 11: de berg gaat open en de doden worden binnengevraagd",
"de Þrælaskriður uit de Eyrbyggja saga — de Slavenhellingen",
"Geirríður uit de Eyrbyggja saga, beschuldigd van nachtrijden",
"de drie wensen, pas in 1955 voor het eerst opgeschreven",
"de aanklacht als kveldriða, afgehandeld in de rechtszaal in plaats van op de brandstapel",
"beekforel van drie tot zes pond en riddervis langs de lavarand",
"vijftigduizend ton haring, twee keer in zes weken",
"de zeehonden die kantooruren aanhouden",
"de kolonist vernoemd naar de richting waar hij niet heen wilde",
"de kerk van 1856–58, de laatste van zijn soort die er nog staat",
"Þórólfurs heilige berg: niemand mocht er ongewassen naar kijken",
"de brouwerij vernoemd naar een sagadichter",
"de volksvergadering die al vóór het Alþingi bijeenkwam",
"een aanklacht wegens hekserij die uitliep op een rechtszaak, niet op een vuur",
"de pijlpuntberg uit *Game of Thrones*",
"🍽️ Eten & drinken",
"hákarl, en waarom de haai eerst goed moet rotten voordat hij veilig is",
"🕰️ Geschiedenis",
"de enige waterval in een land vol benoemd water die nooit een naam kreeg",
"de draaikolk die een boerenzoon opmerkte en waar niemand achteraan ging",
"🔤 Taal & namen",
"'riviervallen' — IJslands voor 'we hebben geen moeite gedaan'",
])
