#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr16 import write

write("de", [
"Schauen Sie rechts auf 1 Uhr — der Grat über dem Sand, mit dem Hof oben drauf.",
"Der Vulkan holte sich im November 1660 die Kirche und den Hof, also bauten sie ihn weiter oben wieder auf und blieben.",
"Wetter-Alternative (wenn der Hang verhangen ist): „Der Hof ist da irgendwo im Grau — und genau darum geht es. Er wurde absichtlich aus der Reichweite des Wassers gebaut.“",
"Ein Hof, der angehoben und versetzt wurde, weil **der Vulkan immer wieder auf ihn zielte** — und die Flut, die es tat, ist fast stundengenau überliefert.",
"**Höfðabrekka** stand unten auf dem flachen Land unterhalb dieses Hangs. Am **3. November 1660** erreichte ihn Katlas Flut — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — und am **8. und 9. November** kam die größte Welle: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **sie riss die Kirche und die meisten Hofgebäude fort.**",
"Sie bauten ihn **oben auf dem Grat selbst** wieder auf — dort steht er heute noch, und genau dorthin schauen Sie. Der Hof behielt seinen Namen und wechselte die Adresse.",
"Das ist das Muster an dieser ganzen Küste, und man sollte es benennen: Die Leute hier geben einen Ort nicht auf, sie **verschieben ihn den Hang hinauf und machen weiter.**",
"Alles zwischen hier und dem Meer ist der Grund — **Mýrdalssandur**, eine schwarze Ebene, die es nur gibt, weil Katla immer wieder einen ganzen Gletscher darüber ausgeleert hat.",
"der Hof, der nach der Flut von 1660 weiter oben wieder aufgebaut wurde",
"die Gletscherflut, die ihn mitnahm",
"Schauen Sie nach vorn — Vík. Da unten hat er gelebt, auf Suður-Vík, ab 1809.",
"Die richtige Antwort über sich bewegendes Eis, 1794 von einem Landarzt aufgeschrieben — und **105 Jahre nach seinem Tod** gedruckt.",
"Er fand heraus, wie sich Gletscher bewegen, während er bei genau diesem Wetter von Hof zu Hof ritt — und die Welt kam 1945 dazu, es zu lesen.",
"Wetter-Alternative (wenn das Eis verdeckt ist): „Es ist alles da drin unter der Wolke. Er war bei genau so einem Wetter draußen, auf einem Pferd, mit einem Notizbuch.“",
"**1794** stand ein Landarzt vor einer Gletscherzunge und fand etwas heraus, das in Europa noch niemand hatte: **Gletscher fließen.** Sie stehen nicht starr. **Sie bewegen sich wie etwas Dickes, Halbgeschmolzenes** — und er war damit rund hundert Jahre zu früh.",
"**Sveinn Pálsson**, **1762–1840.** Er machte im **Frühjahr 1791 in Kopenhagen einen naturwissenschaftlichen Abschluss** — als Erster in Dänemark, der diese Prüfung ablegte — und fuhr heim mit dem Vorsatz, die medizinische Hälfte später fertig zu machen. Fertig gemacht hat er sie nie. Praktiziert hat er trotzdem, sein Leben lang.",
"**1799** wurde ein neuer Arztbezirk eingerichtet, der **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla und die Westmännerinseln** umfasste. Er trat ihn **1800** an, zog **1809 nach Suður-Vík in Mýrdalur** — in das Dorf, in das wir gerade hineinfahren — und blieb dort bis zu seinem Tod **1840.**",
"Die Gletscher waren seine eigene Zeit, nicht der Beruf. Am **Kvíárjökull im Jahr 1794** sah er die bogenförmigen Risse über dem Eis und schrieb, es habe sich bewegt *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **halb geschmolzen, wie eine dickflüssige, zähe Masse.** Das ist die moderne Antwort: Eis verformt sich unter seinem eigenen Gewicht und kriecht bergab.",
"Europa bekam es nie zu lesen. Sein ***Ferðabók*** und die Gletscherabhandlung ***Jöklaritið*** **blieben Manuskript und wurden erst 1945 gedruckt**, übersetzt von **Jón Eyþórsson, Pálmi Hannesson und Steindór Steindórsson**; die englische Ausgabe kam **2004.** 1945 war der Ruhm für die Gletscherbewegung längst anderswo.",
"Und seien Sie genau bei dem, was Guides falsch machen: **Er war nicht Islands erster Arzt.** Das war sein Schwiegervater, **Bjarni Pálsson**, der erste *landlæknir*. Sveinn selbst sprang kurz als amtierender *landlæknir* ein, **1803–04.**",
"der Distriktarzt in Vík, 1762–1840",
"die Gletscherzunge, die er 1794 beschrieb",
"seine Gletscherabhandlung, gedruckt 1945",
"der Hof in Vík, auf dem er ab 1809 lebte",
])

write("fr", [
"Regardez à droite, à 1 heure — la crête au-dessus du sable, avec la ferme tout en haut.",
"Le volcan a emporté l'église et la ferme en novembre 1660 ; ils l'ont rebâtie plus haut sur la pente et sont restés.",
"Variante météo (si la pente est bouchée) : « La ferme est quelque part là-dedans, dans la purée — et c'est exactement l'idée. On l'a mise là-haut exprès, hors de portée de l'eau. »",
"Une ferme qu'on a soulevée et déplacée parce que **le volcan n'arrêtait pas de la viser** — et la crue qui l'a fait est consignée presque heure par heure.",
"**Höfðabrekka** se tenait en contrebas, sur le terrain plat au pied de cette pente. Le **3 novembre 1660**, la crue de Katla l'atteint — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — et les **8 et 9 novembre** arrive la plus grosse vague : *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **elle emporte l'église et la plupart des bâtiments de la ferme.**",
"Ils l'ont rebâtie **sur la crête elle-même** — là où elle est encore, et là où vous regardez. La ferme a gardé son nom et changé d'adresse.",
"C'est le schéma de toute cette côte, et il mérite d'être nommé : ici on n'abandonne pas un lieu, on **le remonte de quelques mètres et on continue.**",
"Tout ce qu'il y a entre nous et la mer en est la raison — **Mýrdalssandur**, une plaine noire qui n'existe que parce que Katla y a vidé un glacier, encore et encore.",
"la ferme rebâtie plus haut après la crue de 1660",
"la crue glaciaire qui l'a emportée",
"Regardez devant — Vík. C'est là-bas qu'il vivait, à Suður-Vík, à partir de 1809.",
"La bonne réponse sur le mouvement de la glace, écrite en 1794 par un médecin de campagne, et imprimée **105 ans après sa mort.**",
"Il a compris comment les glaciers se déplacent en allant de ferme en ferme par ce temps-là — et le monde a fini par le lire en 1945.",
"Variante météo (si la glace est cachée) : « Tout est là-dedans, sous le nuage. Il sortait par exactement ce temps-là, à cheval, avec un carnet. »",
"En **1794**, un médecin de campagne s'est planté devant une langue glaciaire et a compris ce que personne en Europe n'avait compris : **les glaciers coulent.** Ils ne sont pas figés. **Ils avancent comme une matière épaisse et à moitié fondue** — et il avait environ un siècle d'avance.",
"**Sveinn Pálsson**, **1762–1840.** Il obtient au **printemps 1791, à Copenhague, un diplôme de sciences naturelles** — le premier au Danemark à passer cet examen — et rentre chez lui en se promettant de finir la moitié médicale plus tard. Il ne l'a jamais finie. Il a soigné quand même, toute sa vie.",
"En **1799**, on crée un nouveau district médical couvrant **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla et les îles Vestmann.** Il le prend en **1800**, s'installe **à Suður-Vík, dans le Mýrdalur, en 1809** — le village où nous entrons — et y reste jusqu'à sa mort en **1840.**",
"Les glaciers, c'était son temps à lui, pas son métier. Au **Kvíárjökull, en 1794**, il regarde les fissures courbes qui traversent la glace et écrit qu'elle a bougé *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **à moitié fondue, comme une matière épaisse et visqueuse.** C'est la réponse moderne : la glace se déforme sous son propre poids et flue vers le bas.",
"L'Europe ne l'a jamais lu. Son ***Ferðabók*** et le traité glaciaire ***Jöklaritið*** **sont restés à l'état de manuscrit et n'ont été imprimés qu'en 1945**, traduits par **Jón Eyþórsson, Pálmi Hannesson et Steindór Steindórsson** ; l'édition anglaise est venue en **2004.** En 1945, le mérite de l'écoulement glaciaire était parti ailleurs depuis longtemps.",
"Et soyons exacts sur ce que les guides ratent : **il n'a pas été le premier médecin d'Islande.** C'était son beau-père, **Bjarni Pálsson**, le premier *landlæknir*. Sveinn a lui-même assuré l'intérim de *landlæknir*, brièvement, en **1803–04.**",
"le médecin de district à Vík, 1762–1840",
"la langue glaciaire qu'il a décrite en 1794",
"son traité sur les glaciers, imprimé en 1945",
"la ferme de Vík où il a vécu à partir de 1809",
])

write("es", [
"Miren a la derecha, a la 1 en punto — la loma por encima de la arena, con la granja arriba del todo.",
"El volcán se llevó la iglesia y la granja en noviembre de 1660, así que la reconstruyeron más arriba y se quedaron.",
"Alternativa con mal tiempo (si la ladera está tapada): «La granja está ahí dentro, en esa niebla — y ese es justo el asunto. La pusieron arriba a propósito, fuera del alcance del agua.»",
"Una granja a la que levantaron y mudaron porque **el volcán no dejaba de apuntarle** — y la riada que lo hizo está registrada casi hora por hora.",
"**Höfðabrekka** estaba en el terreno bajo, al pie de esta ladera. El **3 de noviembre de 1660** la riada de Katla llegó hasta ella — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — y el **8 y 9 de noviembre** llegó la ola mayor: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **se llevó la iglesia y casi todos los edificios de la granja.**",
"La reconstruyeron **arriba, en la loma misma** — donde sigue estando, y hacia donde ustedes miran. La granja conservó el nombre y cambió de dirección.",
"Ese es el patrón de toda esta costa, y merece nombrarse: aquí la gente no abandona un sitio, lo **sube ladera arriba y sigue adelante.**",
"Todo lo que hay entre aquí y el mar es la razón — **Mýrdalssandur**, una llanura negra que existe porque Katla ha vaciado un glaciar sobre ella una y otra vez.",
"la granja reconstruida ladera arriba tras la riada de 1660",
"la riada glaciar que se la llevó",
"Miren al frente — Vík. Ahí abajo vivía él, en Suður-Vík, desde 1809.",
"La respuesta correcta sobre el hielo en movimiento, escrita en 1794 por un médico rural e impresa **105 años después de su muerte.**",
"Descubrió cómo se mueven los glaciares mientras iba a caballo de granja en granja con este mismo tiempo — y el mundo se puso a leerlo en 1945.",
"Alternativa con mal tiempo (si el hielo está tapado): «Está todo ahí dentro, bajo la nube. Él salía con exactamente este tiempo, a caballo, con un cuaderno.»",
"En **1794** un médico rural se plantó ante una lengua glaciar y dedujo algo que nadie en Europa tenía: **los glaciares fluyen.** No están congelados y quietos. **Se mueven como algo espeso y medio derretido** — y él iba unos cien años por delante.",
"**Sveinn Pálsson**, **1762–1840.** Sacó en la **primavera de 1791, en Copenhague, un título de ciencias naturales** — el primero en Dinamarca que se examinó de aquello — y volvió a casa con la idea de terminar más tarde la mitad médica. Nunca la terminó. Ejerció igualmente, el resto de su vida.",
"En **1799** se creó un nuevo distrito médico que abarcaba **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla y las Islas Vestman.** Lo asumió en **1800**, se mudó a **Suður-Vík, en Mýrdalur, en 1809** — el pueblo al que estamos entrando — y allí siguió hasta su muerte en **1840.**",
"Los glaciares eran su tiempo libre, no el trabajo. En **Kvíárjökull, en 1794**, miró las grietas curvas que cruzaban el hielo y escribió que se había movido *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **medio derretido, como una sustancia espesa y viscosa.** Esa es la respuesta moderna: el hielo se deforma bajo su propio peso y repta cuesta abajo.",
"Europa no llegó a leerlo. Su ***Ferðabók*** y el tratado glaciar ***Jöklaritið*** **se quedaron en manuscrito y no se imprimieron hasta 1945**, traducidos por **Jón Eyþórsson, Pálmi Hannesson y Steindór Steindórsson**; la edición inglesa llegó en **2004.** Para 1945 el mérito del flujo glaciar se había ido a otra parte hacía mucho.",
"Y seamos exactos con lo que los guías suelen fallar: **no fue el primer médico de Islandia.** Ese fue su suegro, **Bjarni Pálsson**, el primer *landlæknir*. El propio Sveinn ejerció brevemente de *landlæknir* interino en **1803–04.**",
"el médico de distrito en Vík, 1762–1840",
"la lengua glaciar que describió en 1794",
"su tratado sobre los glaciares, impreso en 1945",
"la granja de Vík en la que vivió desde 1809",
])

write("it", [
"Guardate a destra, a ore 1 — il crinale sopra la sabbia, con la fattoria in cima.",
"Il vulcano si è preso la chiesa e la fattoria nel novembre 1660, così l'hanno ricostruita più in alto e sono rimasti.",
"Alternativa col brutto tempo (se il pendio è coperto): «La fattoria è lì dentro, in quella nebbia — ed è esattamente il punto. L'hanno messa lassù apposta, fuori dalla portata dell'acqua.»",
"Una fattoria presa di peso e spostata perché **il vulcano continuava a mirarle addosso** — e la piena che l'ha fatto è registrata quasi ora per ora.",
"**Höfðabrekka** stava sul terreno basso, sotto questo pendio. Il **3 novembre 1660** la piena di Katla la raggiunse — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — e l'**8 e 9 novembre** arrivò l'onda più grande: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **si portò via la chiesa e quasi tutti gli edifici della fattoria.**",
"L'hanno ricostruita **sul crinale stesso** — dove sta ancora, e dove state guardando. La fattoria ha tenuto il nome e cambiato indirizzo.",
"È lo schema di tutta questa costa, e vale la pena dirlo: qui la gente non abbandona un posto, lo **sposta più in alto e tira avanti.**",
"Tutto quello che c'è fra qui e il mare è il motivo — **Mýrdalssandur**, una piana nera che esiste perché Katla ci ha svuotato sopra un ghiacciaio, più volte.",
"la fattoria ricostruita più in alto dopo la piena del 1660",
"la piena glaciale che se la portò via",
"Guardate avanti — Vík. Viveva laggiù, a Suður-Vík, dal 1809.",
"La risposta giusta sul ghiaccio che si muove, scritta nel 1794 da un medico condotto e stampata **105 anni dopo la sua morte.**",
"Ha capito come si muovono i ghiacciai mentre andava a cavallo di fattoria in fattoria con questo tempo — e il mondo si è messo a leggerlo nel 1945.",
"Alternativa col brutto tempo (se il ghiaccio è nascosto): «È tutto lì dentro, sotto la nuvola. Lui usciva esattamente con questo tempo, a cavallo, con un taccuino.»",
"Nel **1794** un medico di campagna si piantò davanti a una lingua glaciale e capì una cosa che in Europa nessuno aveva capito: **i ghiacciai scorrono.** Non stanno fermi. **Si muovono come qualcosa di denso e mezzo sciolto** — ed era in anticipo di circa un secolo.",
"**Sveinn Pálsson**, **1762–1840.** Nella **primavera del 1791 si laureò a Copenaghen in scienze naturali** — il primo in Danimarca a sostenere quell'esame — e tornò a casa con l'idea di finire più tardi la metà medica. Non la finì mai. Fece il medico lo stesso, per tutta la vita.",
"Nel **1799** fu creato un nuovo distretto medico che copriva **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla e le isole Vestmann.** Lo assunse nel **1800**, si trasferì a **Suður-Vík, nel Mýrdalur, nel 1809** — il paese in cui stiamo entrando — e vi restò fino alla morte, nel **1840.**",
"I ghiacciai erano il suo tempo libero, non il lavoro. Al **Kvíárjökull, nel 1794**, guardò le fratture curve che attraversavano il ghiaccio e scrisse che si era mosso *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **mezzo sciolto, come una sostanza densa e viscosa.** È la risposta moderna: il ghiaccio si deforma sotto il proprio peso e scivola a valle.",
"L'Europa non lo lesse mai. Il suo ***Ferðabók*** e il trattato sui ghiacciai ***Jöklaritið*** **restarono manoscritti e non furono stampati fino al 1945**, tradotti da **Jón Eyþórsson, Pálmi Hannesson e Steindór Steindórsson**; l'edizione inglese arrivò nel **2004.** Nel 1945 il merito del flusso glaciale era finito altrove da un pezzo.",
"E siamo precisi su quello che le guide sbagliano: **non fu il primo medico d'Islanda.** Quello fu suo suocero, **Bjarni Pálsson**, il primo *landlæknir*. Sveinn fece lui stesso da *landlæknir* reggente, brevemente, nel **1803–04.**",
"il medico condotto di Vík, 1762–1840",
"la lingua glaciale che descrisse nel 1794",
"il suo trattato sui ghiacciai, stampato nel 1945",
"la fattoria di Vík in cui visse dal 1809",
])

write("nl", [
"Kijk rechts op 1 uur — de rug boven het zand, met de boerderij er bovenop.",
"De vulkaan nam de kerk en de boerderij in november 1660, dus bouwden ze hem hogerop opnieuw en bleven.",
"Weeralternatief (als de helling wegvalt): „De boerderij zit ergens in die soep — en dat is precies het punt. Hij is daar expres neergezet, buiten bereik van het water.”",
"Een boerderij die is opgetild en verplaatst omdat **de vulkaan er telkens weer op mikte** — en de vloed die het deed is bijna uur voor uur opgeschreven.",
"**Höfðabrekka** stond op het lage land onder deze helling. Op **3 november 1660** bereikte Katla's vloed hem — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — en op **8 en 9 november** kwam de grootste golf: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **die nam de kerk en de meeste boerderijgebouwen mee.**",
"Ze bouwden hem **boven op de rug zelf** opnieuw — waar hij nog steeds staat, en waar u nu naar kijkt. De boerderij hield haar naam en wisselde van adres.",
"Dat is het patroon langs deze hele kust, en het mag benoemd worden: mensen hier geven een plek niet op, ze **schuiven hem de helling op en gaan door.**",
"Alles tussen hier en de zee is de reden — **Mýrdalssandur**, een zwarte vlakte die alleen bestaat omdat Katla er keer op keer een gletsjer overheen heeft leeggegooid.",
"de boerderij die na de vloed van 1660 hogerop werd herbouwd",
"de gletsjervloed die hem meenam",
"Kijk vooruit — Vík. Daar beneden woonde hij, op Suður-Vík, vanaf 1809.",
"Het juiste antwoord over bewegend ijs, in 1794 opgeschreven door een plattelandsdokter en gedrukt **105 jaar na zijn dood.**",
"Hij kwam erachter hoe gletsjers bewegen terwijl hij in precies dit weer van boerderij naar boerderij reed — en de wereld kwam er in 1945 aan toe het te lezen.",
"Weeralternatief (als het ijs verstopt zit): „Het zit er allemaal in, onder die wolk. Hij ging er in precies dit weer op uit, te paard, met een notitieboekje.”",
"In **1794** stond een plattelandsdokter voor een gletsjertong en kwam erachter wat niemand in Europa had: **gletsjers stromen.** Ze staan niet stil bevroren. **Ze bewegen als iets diks en halfgesmoltens** — en hij was er zo'n eeuw te vroeg mee.",
"**Sveinn Pálsson**, **1762–1840.** Hij haalde in het **voorjaar van 1791 in Kopenhagen een graad in de natuurwetenschappen** — de eerste in Denemarken die dat examen aflegde — en ging naar huis met het plan de medische helft later af te maken. Afmaken deed hij het nooit. Hij dokterde toch, zijn leven lang.",
"In **1799** werd een nieuw artsendistrict ingesteld dat **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla en de Westmaneilanden** omvatte. Hij nam het in **1800** aan, verhuisde in **1809 naar Suður-Vík in Mýrdalur** — het dorp waar we nu binnenrijden — en bleef daar tot hij in **1840** stierf.",
"De gletsjers waren zijn eigen tijd, niet zijn werk. Bij de **Kvíárjökull in 1794** keek hij naar de gebogen scheuren over het ijs en schreef dat het bewogen had *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **halfgesmolten, als een dikke stroperige massa.** Dat is het moderne antwoord: ijs vervormt onder zijn eigen gewicht en kruipt bergaf.",
"Europa kreeg het nooit te lezen. Zijn ***Ferðabók*** en de gletsjerverhandeling ***Jöklaritið*** **bleven in manuscript en werden pas in 1945 gedrukt**, vertaald door **Jón Eyþórsson, Pálmi Hannesson en Steindór Steindórsson**; de Engelse editie kwam in **2004.** In 1945 was de eer voor gletsjerstroming allang elders beland.",
"En wees nauwkeurig op het punt waar gidsen de fout in gaan: **hij was niet IJslands eerste arts.** Dat was zijn schoonvader, **Bjarni Pálsson**, de eerste *landlæknir*. Sveinn viel zelf kort in als waarnemend *landlæknir*, in **1803–04.**",
"de districtsarts in Vík, 1762–1840",
"de gletsjertong die hij in 1794 beschreef",
"zijn gletsjerverhandeling, gedrukt in 1945",
"de boerderij in Vík waar hij vanaf 1809 woonde",
])
