#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr15 import write

write("pt", [
"Bem a leste, a doze quilómetros — a enorme montanha de topo plano no horizonte.",
"o médico rural que descobriu como se movem os glaciares",
"a quinta que se mudou encosta acima",
"uma cascata sobre lava porosa cujo nome ninguém chegou a escrever",
"um lago alimentado por um rio e sem qualquer saída à superfície",
"um campo de lava com 4.000 anos, saído de quatro cones do Ljósufjöll",
"o aterro de 2004 e o que fez a um fiorde",
"o gelo subtraiu uma paisagem inteira e deixou de pé o melhor bocado",
"conchas marinhas seladas sob lava datada de cerca de 1,1 milhões de anos",
"a cervejeira baptizada com o nome do poeta e brigão da Egils saga",
"os dois berserkers e a estrada que lhes foi paga com um banho",
"Eyrbyggja saga, capítulo 11: a montanha abre-se e os mortos são recebidos lá dentro",
"os Þrælaskriður da Eyrbyggja saga — as Vertentes dos Escravos",
"Geirríður da Eyrbyggja saga, acusada de cavalgar de noite",
"os três desejos, postos por escrito pela primeira vez em 1955",
"a acusação de kveldriða, resolvida em tribunal e não na fogueira",
"trutas de três a seis libras e sálvelinos junto ao bordo da lava",
"cinquenta mil toneladas de arenque, duas vezes em seis semanas",
"as focas que cumprem horário de escritório",
"o colono baptizado com a direcção para onde se recusou a ir",
"a igreja de 1856–58, a última do seu género ainda de pé",
"a montanha sagrada de Þórólfur: ninguém a podia olhar sem se ter lavado",
"a cervejeira baptizada com o nome de um poeta das sagas",
"a assembleia que se reunia antes de existir o Alþingi",
"uma acusação de bruxaria que acabou em tribunal, não em fogo",
"a montanha em ponta de seta de *Game of Thrones*",
"🍽️ Comida e bebida",
"o hákarl, e porque é que o tubarão tem de apodrecer bem antes de ser seguro",
"🕰️ História",
"a única cascata, num país onde toda a água tem nome, que nunca recebeu um",
"o remoinho que um filho de lavradores reparou e que ninguém foi investigar",
"🔤 Língua e nomes",
"«queda do rio» — islandês para «não nos demos ao trabalho»",
])

write("pl", [
"Dokładnie na wschód, dwanaście kilometrów stąd — potężna góra o płaskim szczycie na horyzoncie.",
"wiejski lekarz, który odkrył, jak poruszają się lodowce",
"gospodarstwo, które przeniosło się wyżej pod górę",
"wodospad na porowatej lawie, którego nazwy nikt nigdy nie zapisał",
"jezioro zasilane rzeką i bez żadnego odpływu na powierzchni",
"pole lawy sprzed 4000 lat, z czterech stożków systemu Ljósufjöll",
"grobla z 2004 roku i to, co zrobiła fiordowi",
"lód odjął cały krajobraz i zostawił stojący najlepszy kawałek",
"muszle morskie zapieczętowane pod lawą datowaną na około 1,1 miliona lat",
"browar nazwany imieniem poety i awanturnika z Egils saga",
"dwaj berserkowie i droga, za którą zapłacono im kąpielą",
"Eyrbyggja saga, rozdział 11: góra otwiera się i zmarłych zaprasza się do środka",
"Þrælaskriður z Eyrbyggja saga — Piargi Niewolników",
"Geirríður z Eyrbyggja saga, oskarżona o nocne ujeżdżanie",
"trzy życzenia, spisane po raz pierwszy w 1955 roku",
"oskarżenie o bycie kveldriða, rozstrzygnięte w sądzie, a nie na stosie",
"pstrągi potokowe od trzech do sześciu funtów i golce wzdłuż krawędzi lawy",
"pięćdziesiąt tysięcy ton śledzi, dwa razy w ciągu sześciu tygodni",
"foki, które trzymają się godzin urzędowania",
"osadnik nazwany od kierunku, w którym nie chciał iść",
"kościół z lat 1856–58, ostatni tego rodzaju, który jeszcze stoi",
"święta góra Þórólfura: nikt nie mógł na nią spojrzeć nieumyty",
"browar nazwany imieniem poety sag",
"zgromadzenie, które obradowało jeszcze przed Alþingi",
"oskarżenie o czary, które skończyło się rozprawą, a nie ogniem",
"góra w kształcie grotu strzały z *Gry o tron*",
"🍽️ Jedzenie i picie",
"hákarl i to, dlaczego rekin musi najpierw porządnie zgnić, żeby był bezpieczny",
"🕰️ Historia",
"jedyny wodospad w kraju, gdzie każda woda ma nazwę, który nigdy jej nie dostał",
"wir, który zauważył chłopak z gospodarstwa i którego nikt nie sprawdził",
"🔤 Język i nazwy",
"„wodospad rzeki” — po islandzku znaczy „nie chciało nam się”",
])

write("da", [
"Stik øst, tolv kilometer ude — det massive bjerg med den flade top i horisonten.",
"landlægen, der regnede ud, hvordan gletsjere bevæger sig",
"gården, der flyttede op ad bakken",
"et vandfald på porøs lava, som ingen nogensinde fik skrevet navnet på",
"en sø, der fødes af en flod og ikke har noget afløb på overfladen",
"et 4.000 år gammelt lavafelt fra fire kegler i Ljósufjöll",
"dæmningen fra 2004 og hvad den gjorde ved en fjord",
"isen trak et helt landskab fra og lod det bedste stykke blive stående",
"havmuslinger forseglet under lava dateret til omkring 1,1 millioner år",
"bryggeriet opkaldt efter digteren og slagsbroderen fra Egils saga",
"de to bersærker og vejen, de fik betalt med et bad",
"Eyrbyggja saga, kapitel 11: bjerget åbner sig, og de døde bydes indenfor",
"Þrælaskriður fra Eyrbyggja saga — Trælleskredet",
"Geirríður fra Eyrbyggja saga, anklaget for at ride om natten",
"de tre ønsker, første gang skrevet ned i 1955",
"anklagen om at være kveldriða, afgjort i retten i stedet for på bålet",
"bækørred på tre til seks pund og fjeldørred langs lavakanten",
"halvtreds tusind tons sild, to gange på seks uger",
"sælerne, der holder kontortid",
"landnamsmanden opkaldt efter den retning, han ikke ville",
"kirken fra 1856–58, den sidste af sin slags der stadig står",
"Þórólfurs hellige bjerg: ingen måtte se på det uvasket",
"bryggeriet opkaldt efter en sagadigter",
"tinget, der mødtes før Alþingi overhovedet fandtes",
"en anklage om hekseri, der endte i retten og ikke i ilden",
"pilespidsbjerget fra *Game of Thrones*",
"🍽️ Mad og drikke",
"hákarl — og hvorfor hajen først skal rådne ordentligt, før den er sikker",
"🕰️ Historie",
"det ene vandfald i et land, hvor alt vand har navne, som aldrig fik et",
"hvirvlen, som en bondesøn lagde mærke til, og som ingen fulgte op på",
"🔤 Sprog og navne",
"„flodfald“ — islandsk for „vi gad ikke“",
])

write("sv", [
"Rakt österut, tolv kilometer bort — det massiva berget med platt topp vid horisonten.",
"lantläkaren som kom på hur glaciärer rör sig",
"gården som flyttade uppför backen",
"ett vattenfall på porös lava som ingen någonsin skrev ner namnet på",
"en sjö som matas av en älv och saknar utlopp ovan jord",
"ett 4 000 år gammalt lavafält från fyra koner i Ljósufjöll",
"vägbanken från 2004 och vad den gjorde med en fjord",
"isen subtraherade ett helt landskap och lämnade det bästa stycket kvar",
"havsmusslor förseglade under lava daterad till omkring 1,1 miljoner år",
"bryggeriet uppkallat efter poeten och slagskämpen i Egils saga",
"de två bärsärkarna och vägen de fick betalt för med ett bad",
"Eyrbyggja saga, kapitel 11: berget öppnar sig och de döda bjuds in",
"Þrælaskriður ur Eyrbyggja saga — Trälrasen",
"Geirríður ur Eyrbyggja saga, anklagad för att rida om natten",
"de tre önskningarna, nedtecknade för första gången 1955",
"anklagelsen om att vara kveldriða, avgjord i domstol i stället för på bål",
"bäcköring på tre till sex skålpund och röding längs lavakanten",
"femtiotusen ton sill, två gånger på sex veckor",
"sälarna som håller kontorstid",
"nybyggaren uppkallad efter riktningen han vägrade ta",
"kyrkan från 1856–58, den sista i sitt slag som står kvar",
"Þórólfurs heliga berg: ingen fick titta på det otvättad",
"bryggeriet uppkallat efter en sagadiktare",
"tinget som möttes innan Alþingi ens fanns",
"en anklagelse om trolldom som slutade i domstol och inte i eld",
"pilspetsberget från *Game of Thrones*",
"🍽️ Mat och dryck",
"hákarl — och varför hajen först måste ruttna ordentligt för att vara ofarlig",
"🕰️ Historia",
"det enda vattenfallet i ett land där allt vatten har namn som aldrig fick ett",
"virveln som en bondpojke lade märke till och som ingen följde upp",
"🔤 Språk och namn",
"”älvfallet” — isländska för ”vi orkade inte”",
])

write("no", [
"Rett øst, tolv kilometer unna — det massive fjellet med flat topp i horisonten.",
"landsbylegen som fant ut hvordan breer beveger seg",
"gården som flyttet oppover bakken",
"en foss på porøs lava som ingen noen gang skrev ned navnet på",
"et vann som mates av en elv og ikke har noe avløp på overflaten",
"et 4 000 år gammelt lavafelt fra fire kjegler i Ljósufjöll",
"fyllingen fra 2004 og hva den gjorde med en fjord",
"isen trakk fra et helt landskap og lot det beste stykket bli stående",
"havskjell forseglet under lava datert til omkring 1,1 millioner år",
"bryggeriet oppkalt etter dikteren og slåsskjempen i Egils saga",
"de to berserkene og veien de fikk betalt for med et bad",
"Eyrbyggja saga, kapittel 11: fjellet åpner seg og de døde blir budt inn",
"Þrælaskriður fra Eyrbyggja saga — Trellskredet",
"Geirríður fra Eyrbyggja saga, anklaget for å ri om natten",
"de tre ønskene, først skrevet ned i 1955",
"anklagen om å være kveldriða, avgjort i retten i stedet for på bålet",
"bekkeørret på tre til seks pund og røye langs lavakanten",
"femti tusen tonn sild, to ganger på seks uker",
"selene som holder kontortid",
"landnåmsmannen oppkalt etter retningen han ikke ville",
"kirken fra 1856–58, den siste av sitt slag som fremdeles står",
"Þórólfurs hellige fjell: ingen fikk se på det uvasket",
"bryggeriet oppkalt etter en sagadikter",
"tinget som møttes før Alþingi i det hele tatt fantes",
"en anklage om trolldom som endte i retten og ikke i ilden",
"pilspissfjellet fra *Game of Thrones*",
"🍽️ Mat og drikke",
"hákarl — og hvorfor haien først må råtne skikkelig for å være trygg",
"🕰️ Historie",
"den ene fossen i et land der alt vann har navn, som aldri fikk et",
"virvelen en gårdsgutt la merke til, og som ingen fulgte opp",
"🔤 Språk og navn",
"«elvefossen» — islandsk for «vi gadd ikke»",
])
