#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr16 import write

write("pt", [
"Olhem à direita, à 1 hora — a crista por cima da areia, com a quinta lá no topo.",
"O vulcão levou a igreja e a quinta em novembro de 1660, por isso reconstruíram-na mais acima e ficaram.",
"Alternativa com mau tempo (se a encosta estiver tapada): «A quinta está algures ali dentro, naquele nevoeiro — e é exatamente essa a questão. Foi posta lá em cima de propósito, fora do alcance da água.»",
"Uma quinta que foi levantada e mudada de sítio porque **o vulcão continuava a apontar-lhe** — e a cheia que o fez está registada quase hora a hora.",
"**Höfðabrekka** ficava no terreno baixo, ao pé desta encosta. A **3 de novembro de 1660** a cheia da Katla chegou-lhe — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — e a **8 e 9 de novembro** veio a onda maior: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **levou a igreja e quase todos os edifícios da quinta.**",
"Reconstruíram-na **em cima da própria crista** — onde ainda está, e para onde estão a olhar. A quinta manteve o nome e mudou de morada.",
"É o padrão de toda esta costa, e vale a pena dizê-lo: aqui as pessoas não abandonam um sítio, **sobem-no pela encosta acima e continuam.**",
"Tudo o que está entre aqui e o mar é a razão — **Mýrdalssandur**, uma planície negra que só existe porque a Katla despejou lá um glaciar, vezes sem conta.",
"a quinta reconstruída encosta acima depois da cheia de 1660",
"a cheia glaciar que a levou",
"Olhem em frente — Vík. Era ali em baixo que ele vivia, em Suður-Vík, a partir de 1809.",
"A resposta certa sobre o gelo em movimento, escrita em 1794 por um médico rural e impressa **105 anos depois de ele morrer.**",
"Percebeu como se movem os glaciares enquanto ia a cavalo de quinta em quinta com este tempo — e o mundo só se pôs a ler aquilo em 1945.",
"Alternativa com mau tempo (se o gelo estiver tapado): «Está tudo ali dentro, debaixo da nuvem. Ele saía exatamente com este tempo, a cavalo, com um caderno.»",
"Em **1794** um médico rural plantou-se à frente de uma língua glaciar e percebeu uma coisa que ninguém na Europa tinha percebido: **os glaciares fluem.** Não estão congelados e parados. **Movem-se como uma coisa espessa e meio derretida** — e ele estava cerca de um século adiantado.",
"**Sveinn Pálsson**, **1762–1840.** Tirou na **primavera de 1791, em Copenhaga, um grau em ciências naturais** — o primeiro na Dinamarca a fazer aquele exame — e voltou para casa com a ideia de acabar mais tarde a metade médica. Nunca a acabou. Exerceu na mesma, o resto da vida.",
"Em **1799** criou-se um novo distrito médico que abrangia **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla e as ilhas Vestman.** Assumiu-o em **1800**, mudou-se para **Suður-Vík, em Mýrdalur, em 1809** — a aldeia em que estamos a entrar — e ficou lá até morrer, em **1840.**",
"Os glaciares eram o tempo dele, não o emprego. No **Kvíárjökull, em 1794**, olhou para as fendas curvas que atravessavam o gelo e escreveu que este se movera *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **meio derretido, como uma substância espessa e viscosa.** É a resposta moderna: o gelo deforma-se sob o próprio peso e rasteja encosta abaixo.",
"A Europa nunca chegou a ler aquilo. O seu ***Ferðabók*** e o tratado glaciar ***Jöklaritið*** **ficaram em manuscrito e só foram impressos em 1945**, traduzidos por **Jón Eyþórsson, Pálmi Hannesson e Steindór Steindórsson**; a edição inglesa veio em **2004.** Em 1945 o crédito pelo fluxo glaciar já tinha ido parar a outro lado havia muito.",
"E sejamos exatos naquilo em que os guias falham: **ele não foi o primeiro médico da Islândia.** Foi o sogro, **Bjarni Pálsson**, o primeiro *landlæknir*. O próprio Sveinn ainda foi *landlæknir* interino, por pouco tempo, em **1803–04.**",
"o médico de distrito em Vík, 1762–1840",
"a língua glaciar que descreveu em 1794",
"o seu tratado sobre glaciares, impresso em 1945",
"a quinta em Vík onde viveu a partir de 1809",
])

write("pl", [
"Spójrzcie w prawo, na godzinę 1 — grzbiet nad piaskiem, a na samej górze gospodarstwo.",
"Wulkan zabrał kościół i gospodarstwo w listopadzie 1660 roku, więc odbudowali je wyżej na stoku i zostali.",
"Wariant na złą pogodę (jeśli stok jest zasłonięty): „Gospodarstwo jest gdzieś tam w tej zupie — i o to właśnie chodzi. Postawiono je wyżej celowo, poza zasięgiem wody”.",
"Gospodarstwo, które podniesiono i przeniesiono, bo **wulkan raz po raz w nie celował** — a powódź, która to zrobiła, jest zapisana niemal godzina po godzinie.",
"**Höfðabrekka** stała na niskim terenie u stóp tego stoku. **3 listopada 1660 roku** dotarła do niej powódź spod Katli — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — a **8 i 9 listopada** przyszła największa fala: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **zabrała kościół i większość zabudowań.**",
"Odbudowali je **na samym grzbiecie** — tam, gdzie stoi do dziś i gdzie właśnie patrzycie. Gospodarstwo zachowało nazwę i zmieniło adres.",
"To wzorzec całego tego wybrzeża i warto go nazwać: ludzie tutaj nie porzucają miejsca, tylko **przesuwają je wyżej po stoku i żyją dalej.**",
"Wszystko między nami a morzem jest tego powodem — **Mýrdalssandur**, czarna równina, która istnieje dlatego, że Katla raz po raz wylała na nią cały lodowiec.",
"gospodarstwo odbudowane wyżej po powodzi z 1660 roku",
"lodowcowa powódź, która je zabrała",
"Spójrzcie przed siebie — Vík. Mieszkał tam na dole, w Suður-Vík, od 1809 roku.",
"Właściwa odpowiedź o ruchu lodu, zapisana w 1794 roku przez wiejskiego lekarza, a wydrukowana **105 lat po jego śmierci.**",
"Zrozumiał, jak poruszają się lodowce, jeżdżąc konno od gospodarstwa do gospodarstwa w dokładnie takiej pogodzie — a świat zabrał się do czytania tego w 1945 roku.",
"Wariant na złą pogodę (jeśli lodu nie widać): „To wszystko jest tam, pod chmurą. On wyjeżdżał dokładnie w taką pogodę, konno, z notesem”.",
"W **1794 roku** wiejski lekarz stanął przed jęzorem lodowca i zrozumiał to, czego nie zrozumiał nikt w Europie: **lodowce płyną.** Nie stoją zamarznięte w miejscu. **Poruszają się jak coś gęstego i na wpół stopionego** — a on wyprzedził wszystkich o jakieś sto lat.",
"**Sveinn Pálsson**, **1762–1840.** **Wiosną 1791 roku zdobył w Kopenhadze dyplom z nauk przyrodniczych** — jako pierwszy w Danii, który zdawał ten egzamin — i wrócił do domu z zamiarem dokończenia później części medycznej. Nigdy jej nie dokończył. Leczył i tak, przez całe życie.",
"W **1799 roku** utworzono nowy okręg lekarski obejmujący **Árnessýslę, Rangárvallasýslę, Vestur-Skaftafellssýslę i Wyspy Westmańskie.** Objął go w **1800 roku**, w **1809 roku przeniósł się do Suður-Vík w Mýrdalur** — do wsi, do której właśnie wjeżdżamy — i został tam aż do śmierci w **1840 roku.**",
"Lodowce były jego własnym czasem, nie pracą. Przy **Kvíárjökull w 1794 roku** przyjrzał się łukowatym szczelinom biegnącym przez lód i zapisał, że lód poruszał się *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **na wpół stopiony, jak gęsta lepka substancja.** To jest współczesna odpowiedź: lód odkształca się pod własnym ciężarem i pełznie w dół.",
"Europa nigdy tego nie przeczytała. Jego ***Ferðabók*** i rozprawa o lodowcach ***Jöklaritið*** **pozostały w rękopisie i wydrukowano je dopiero w 1945 roku**, w przekładzie **Jóna Eyþórssona, Pálmiego Hannessona i Steindóra Steindórssona**; wydanie angielskie ukazało się w **2004 roku.** W 1945 zasługa za odkrycie ruchu lodowców od dawna należała już do kogoś innego.",
"I bądźmy dokładni w tym, co przewodnicy przekręcają: **nie był pierwszym lekarzem Islandii.** Był nim jego teść, **Bjarni Pálsson**, pierwszy *landlæknir*. Sam Sveinn przez krótki czas pełnił obowiązki *landlæknira*, w **1803–04.**",
"lekarz okręgowy w Vík, 1762–1840",
"jęzor lodowca, który opisał w 1794 roku",
"jego rozprawa o lodowcach, wydrukowana w 1945 roku",
"gospodarstwo w Vík, w którym mieszkał od 1809 roku",
])

write("da", [
"Kig til højre klokken 1 — ryggen over sandet, med gården oppe på toppen.",
"Vulkanen tog kirken og gården i november 1660, så byggede de den op igen længere oppe ad bakken og blev boende.",
"Vejr-alternativ (hvis skråningen er væk): „Gården er derinde et sted i suppen — og det er præcis pointen. Den blev bevidst lagt deroppe, uden for vandets rækkevidde.“",
"En gård, der blev løftet op og flyttet, fordi **vulkanen blev ved med at sigte på den** — og det løb, der gjorde det, er nedskrevet næsten time for time.",
"**Höfðabrekka** lå på det lave land neden for denne skråning. Den **3. november 1660** nåede Katlas løb frem til den — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — og den **8.–9. november** kom den største bølge: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **den tog kirken og det meste af gårdens bygninger.**",
"De byggede den op igen **oppe på selve ryggen** — hvor den stadig ligger, og hvor I kigger hen nu. Gården beholdt sit navn og skiftede adresse.",
"Det er mønstret langs hele denne kyst, og det fortjener at blive sagt: folk her opgiver ikke et sted, de **flytter det op ad skråningen og fortsætter.**",
"Alt mellem os og havet er grunden — **Mýrdalssandur**, en sort slette, der kun findes, fordi Katla gang på gang har tømt en gletsjer ud over den.",
"gården, der blev genopbygget længere oppe efter løbet i 1660",
"det gletsjerløb, der tog den",
"Kig fremad — Vík. Dernede boede han, på Suður-Vík, fra 1809.",
"Det rigtige svar om is, der bevæger sig, skrevet ned i 1794 af en landlæge og trykt **105 år efter hans død.**",
"Han regnede ud, hvordan gletsjere bevæger sig, mens han red fra gård til gård i præcis det her vejr — og verden nåede til at læse det i 1945.",
"Vejr-alternativ (hvis isen er skjult): „Det hele ligger derinde under skyen. Han var ude i præcis sådan et vejr, på hesteryg, med en notesbog.“",
"I **1794** stillede en landlæge sig foran en gletsjertunge og regnede ud, hvad ingen i Europa havde regnet ud: **gletsjere flyder.** De står ikke frosset stille. **De bevæger sig som noget tykt og halvsmeltet** — og han var omkring hundrede år for tidligt ude.",
"**Sveinn Pálsson**, **1762–1840.** Han tog i **foråret 1791 en naturvidenskabelig eksamen i København** — som den første i Danmark, der gik op til den — og rejste hjem med den plan at gøre den medicinske halvdel færdig senere. Færdig blev den aldrig. Han praktiserede alligevel, resten af sit liv.",
"I **1799** blev der oprettet et nyt lægedistrikt, der dækkede **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla og Vestmannaøerne.** Han tiltrådte i **1800**, flyttede i **1809 til Suður-Vík i Mýrdalur** — landsbyen vi kører ind i — og blev der til sin død i **1840.**",
"Gletsjerne var hans egen tid, ikke arbejdet. Ved **Kvíárjökull i 1794** så han på de buede sprækker hen over isen og skrev, at den havde bevæget sig *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **halvsmeltet, som et tykt, sejtflydende stof.** Det er det moderne svar: is deformeres under sin egen vægt og kryber nedad.",
"Europa fik det aldrig at læse. Hans ***Ferðabók*** og gletsjerafhandlingen ***Jöklaritið*** **blev liggende i manuskript og blev først trykt i 1945**, oversat af **Jón Eyþórsson, Pálmi Hannesson og Steindór Steindórsson**; den engelske udgave kom i **2004.** I 1945 var æren for gletsjerbevægelse for længst havnet et andet sted.",
"Og lad os være præcise med det, guiderne plejer at ramme forkert: **han var ikke Islands første læge.** Det var hans svigerfar, **Bjarni Pálsson**, den første *landlæknir*. Sveinn var selv kortvarigt fungerende *landlæknir*, i **1803–04.**",
"distriktslægen i Vík, 1762–1840",
"den gletsjertunge, han beskrev i 1794",
"hans gletsjerafhandling, trykt i 1945",
"gården i Vík, han boede på fra 1809",
])

write("sv", [
"Titta till höger, klockan 1 — ryggen ovanför sanden, med gården högst upp.",
"Vulkanen tog kyrkan och gården i november 1660, så de byggde upp den igen längre upp i backen och blev kvar.",
"Väderalternativ (om sluttningen är borta): ”Gården ligger någonstans där inne i soppan — och det är precis poängen. Den lades däruppe med flit, utom räckhåll för vattnet.”",
"En gård som lyftes upp och flyttades för att **vulkanen hela tiden siktade på den** — och floden som gjorde det finns nedtecknad nästan timme för timme.",
"**Höfðabrekka** låg på låglandet nedanför den här sluttningen. Den **3 november 1660** nådde Katlas flod fram — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — och den **8–9 november** kom den största vågen: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **den tog kyrkan och det mesta av gårdens byggnader.**",
"De byggde upp den **uppe på själva ryggen** — där den fortfarande ligger, och dit ni tittar nu. Gården behöll sitt namn och bytte adress.",
"Det är mönstret längs hela den här kusten, och det är värt att säga rakt ut: folk här överger inte en plats, de **flyttar den uppför sluttningen och kör vidare.**",
"Allt mellan oss och havet är skälet — **Mýrdalssandur**, en svart slätt som bara finns för att Katla gång på gång har tömt en glaciär över den.",
"gården som byggdes upp högre efter floden 1660",
"glaciärfloden som tog den",
"Titta rakt fram — Vík. Där nere bodde han, på Suður-Vík, från 1809.",
"Rätt svar om is som rör sig, nedskrivet 1794 av en lantläkare och tryckt **105 år efter hans död.**",
"Han kom på hur glaciärer rör sig medan han red mellan gårdar i precis det här vädret — och världen hann läsa det 1945.",
"Väderalternativ (om isen är dold): ”Allt ligger där inne under molnet. Han var ute i precis det här vädret, till häst, med ett anteckningsblock.”",
"**1794** ställde sig en lantläkare framför en glaciärtunga och kom på något ingen i Europa hade kommit på: **glaciärer flyter.** De står inte frusna stilla. **De rör sig som något tjockt och halvsmält** — och han var ungefär hundra år för tidig.",
"**Sveinn Pálsson**, **1762–1840.** Han tog **våren 1791 en naturvetenskaplig examen i Köpenhamn** — den förste i Danmark som skrev det provet — och åkte hem med tanken att göra klart den medicinska halvan senare. Klart blev det aldrig. Han praktiserade ändå, resten av livet.",
"**1799** inrättades ett nytt läkardistrikt som täckte **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla och Västmannaöarna.** Han tillträdde **1800**, flyttade **1809 till Suður-Vík i Mýrdalur** — byn vi kör in i — och stannade där tills han dog **1840.**",
"Glaciärerna var hans egen tid, inte jobbet. Vid **Kvíárjökull 1794** tittade han på de bågformade sprickorna tvärs över isen och skrev att den hade rört sig *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **halvsmält, som ett tjockt trögflytande ämne.** Det är det moderna svaret: is deformeras under sin egen tyngd och kryper nedför.",
"Europa fick aldrig läsa det. Hans ***Ferðabók*** och glaciäravhandlingen ***Jöklaritið*** **blev liggande i manuskript och trycktes inte förrän 1945**, översatta av **Jón Eyþórsson, Pálmi Hannesson och Steindór Steindórsson**; den engelska utgåvan kom **2004.** 1945 hade äran för glaciärflödet för länge sedan hamnat någon annanstans.",
"Och låt oss vara noga med det guiderna brukar få om bakfoten: **han var inte Islands förste läkare.** Det var hans svärfar, **Bjarni Pálsson**, den förste *landlæknir*. Sveinn var själv tillförordnad *landlæknir* en kort tid, **1803–04.**",
"distriktsläkaren i Vík, 1762–1840",
"glaciärtungan han beskrev 1794",
"hans avhandling om glaciärer, tryckt 1945",
"gården i Vík där han bodde från 1809",
])

write("no", [
"Se til høyre, klokka 1 — ryggen over sanden, med gården oppå.",
"Vulkanen tok kirken og gården i november 1660, så de bygde den opp igjen lenger oppe i bakken og ble boende.",
"Væralternativ (hvis lia er borte): «Gården ligger der inne et sted i grøten — og det er nettopp poenget. Den ble lagt der oppe med vilje, utenfor rekkevidde for vannet.»",
"En gård som ble løftet opp og flyttet fordi **vulkanen stadig siktet på den** — og flommen som gjorde det er nedskrevet nesten time for time.",
"**Höfðabrekka** lå på lavlandet nedenfor denne lia. Den **3. november 1660** nådde Katlas flom fram til den — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — og den **8.–9. november** kom den største bølgen: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **den tok kirken og det meste av gårdsbygningene.**",
"De bygde den opp igjen **oppe på selve ryggen** — der den fremdeles ligger, og dit dere ser nå. Gården beholdt navnet og byttet adresse.",
"Det er mønsteret langs hele denne kysten, og det fortjener å bli sagt: folk her forlater ikke et sted, de **flytter det oppover lia og fortsetter.**",
"Alt mellom oss og havet er grunnen — **Mýrdalssandur**, en svart slette som bare finnes fordi Katla gang på gang har tømt en isbre utover den.",
"gården som ble bygd opp høyere etter flommen i 1660",
"brefloden som tok den",
"Se rett fram — Vík. Der nede bodde han, på Suður-Vík, fra 1809.",
"Det riktige svaret om is som beveger seg, skrevet ned i 1794 av en landsbylege og trykt **105 år etter at han døde.**",
"Han fant ut hvordan breer beveger seg mens han red mellom gårder i akkurat dette været — og verden rakk å lese det i 1945.",
"Væralternativ (hvis isen er skjult): «Alt ligger der inne under skyen. Han var ute i akkurat dette været, til hest, med en notatbok.»",
"I **1794** stilte en landsbylege seg foran en bretunge og fant ut det ingen i Europa hadde funnet ut: **breer flyter.** De står ikke frosset stille. **De beveger seg som noe tykt og halvsmeltet** — og han var rundt hundre år for tidlig ute.",
"**Sveinn Pálsson**, **1762–1840.** Han tok **våren 1791 en naturvitenskapelig grad i København** — den første i Danmark som gikk opp til den eksamenen — og dro hjem med tanke om å fullføre den medisinske halvdelen senere. Fullført ble den aldri. Han praktiserte likevel, resten av livet.",
"I **1799** ble det opprettet et nytt legedistrikt som dekket **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla og Vestmannaøyene.** Han tiltrådte i **1800**, flyttet i **1809 til Suður-Vík i Mýrdalur** — landsbyen vi kjører inn i — og ble der til han døde i **1840.**",
"Breene var hans egen tid, ikke jobben. Ved **Kvíárjökull i 1794** så han på de bueformede sprekkene tvers over isen og skrev at den hadde beveget seg *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **halvsmeltet, som et tykt, seigtflytende stoff.** Det er det moderne svaret: is deformeres under sin egen vekt og kryper nedover.",
"Europa fikk aldri lese det. Hans ***Ferðabók*** og breavhandlingen ***Jöklaritið*** **ble liggende i manuskript og ble ikke trykt før i 1945**, oversatt av **Jón Eyþórsson, Pálmi Hannesson og Steindór Steindórsson**; den engelske utgaven kom i **2004.** I 1945 hadde æren for brebevegelsen for lengst havnet et annet sted.",
"Og la oss være nøyaktige med det guidene pleier å ta feil av: **han var ikke Islands første lege.** Det var svigerfaren, **Bjarni Pálsson**, den første *landlæknir*. Sveinn var selv kort tid fungerende *landlæknir*, i **1803–04.**",
"distriktslegen i Vík, 1762–1840",
"bretungen han beskrev i 1794",
"breavhandlingen hans, trykt i 1945",
"gården i Vík der han bodde fra 1809",
])
