#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr15 import write

write("fi", [
"Suoraan itään, kahdentoista kilometrin päässä — valtava litteähuippuinen vuori taivaanrannassa.",
"maalaislääkäri, joka päätteli miten jäätiköt liikkuvat",
"tila, joka muutti rinnettä ylemmäs",
"vesiputous huokoisella laavalla, jonka nimeä kukaan ei koskaan kirjannut ylös",
"järvi, jota joki ruokkii ja jolla ei ole pinnalla mitään laskua",
"4 000 vuotta vanha laavakenttä neljästä Ljósufjöllin kartiosta",
"vuoden 2004 pengertie ja se, mitä se teki vuonolle",
"jää vähensi kokonaisen maiseman ja jätti parhaan palan pystyyn",
"merisimpukoita laavan alle sinetöitynä, ikä noin 1,1 miljoonaa vuotta",
"panimo, joka on nimetty Egils sagan runoilija-tappelijan mukaan",
"kaksi berserkkiä ja tie, josta heille maksettiin kylvyllä",
"Eyrbyggja saga, luku 11: vuori aukeaa ja kuolleet toivotetaan sisään",
"Eyrbyggja sagan Þrælaskriður — Orjien vyörymät",
"Eyrbyggja sagan Geirríður, jota syytettiin yöratsastuksesta",
"kolme toivomusta, kirjattiin ensi kerran ylös vuonna 1955",
"kveldriða-syyte, joka ratkaistiin oikeudessa eikä roviolla",
"purotaimenia kolmesta kuuteen naulaan ja nieriöitä laavan reunassa",
"viisikymmentätuhatta tonnia silliä, kahdesti kuudessa viikossa",
"hylkeet, jotka pitävät toimistoaikoja",
"uudisasukas, joka nimettiin sen suunnan mukaan johon ei suostunut menemään",
"vuosien 1856–58 kirkko, viimeinen lajissaan joka on yhä pystyssä",
"Þórólfurin pyhä vuori: kukaan ei saanut katsoa sitä peseytymättä",
"panimo, joka on nimetty saagarunoilijan mukaan",
"käräjät, jotka kokoontuivat jo ennen Alþingiä",
"noituussyyte, joka päätyi oikeuteen eikä tuleen",
"nuolenkärkivuori sarjasta *Game of Thrones*",
"🍽️ Ruoka ja juoma",
"hákarl — ja miksi hain on ensin mädännyttävä kunnolla ollakseen turvallista",
"🕰️ Historia",
"maan ainoa vesiputous, jossa kaikella vedellä on nimi, joka ei koskaan saanut omaansa",
"pyörre, jonka talon poika huomasi eikä kukaan käynyt tarkistamassa",
"🔤 Kieli ja nimet",
"”jokiputous” — islanniksi ”emme jaksaneet”",
])

write("is", [
"Beint í austur, tólf kílómetra í burtu — stóra flatkollótta fjallið við sjóndeildarhringinn.",
"héraðslæknirinn sem komst að því hvernig jöklar hreyfast",
"bærinn sem flutti sig ofar í hlíðina",
"foss á gropnu hrauni sem enginn nennti að skrá nafnið á",
"vatn sem á sér innrennsli en ekkert afrennsli á yfirborði",
"4.000 ára gamalt hraun úr fjórum gígum í Ljósufjallakerfinu",
"vegfyllingin frá 2004 og hvað hún gerði firðinum",
"ísinn dró heilt landslag frá og skildi besta bitann eftir standandi",
"sæskeljar innsiglaðar undir hrauni sem er talið um 1,1 milljón ára",
"brugghúsið sem heitir eftir skáldinu og slagsmálahundinum úr Egils sögu",
"berserkirnir tveir og gatan sem þeir fengu bað að launum fyrir",
"Eyrbyggja saga, 11. kafli: fjallið opnast og dauðum er boðið inn",
"Þrælaskriður Eyrbyggju — skriðurnar sem draga nafn af þrælum",
"Geirríður í Eyrbyggju, sökuð um að vera kveldriða",
"óskirnar þrjár, fyrst skráðar árið 1955",
"kveldriðuákæran, sem var svarað fyrir dómi en ekki á báli",
"urriði á þrjú til sex pund og bleikja meðfram hraunkantinum",
"fimmtíu þúsund tonn af síld, tvisvar á sex vikum",
"selirnir sem halda skrifstofutíma",
"landnámsmaðurinn sem heitir eftir áttinni sem hann vildi ekki fara í",
"kirkjan frá 1856–58, sú síðasta sinnar tegundar sem enn stendur",
"helgafell Þórólfs: enginn mátti líta á það óþveginn",
"brugghúsið sem heitir eftir sagnaskáldi",
"þingið sem kom saman áður en Alþingi varð til",
"galdraákæra sem endaði fyrir dómi en ekki í eldi",
"örvaroddsfjallið úr *Game of Thrones*",
"🍽️ Matur og drykkur",
"hákarl — og hvers vegna hákarlinn verður að kæsast rétt áður en óhætt er að borða hann",
"🕰️ Saga",
"eini fossinn í landi þar sem allt vatn ber nafn sem fékk aldrei sitt eigið",
"iðan sem bóndasonur tók eftir og enginn kannaði nánar",
"🔤 Tungumál og örnefni",
"„fossá“ — nafn sem segir nákvæmlega ekkert umfram það sem blasir við",
])

write("zh", [
"正东方向，十二公里外——地平线上那座巨大的平顶山。",
"那位弄明白冰川如何移动的乡村医生",
"那座往山上搬家的农场",
"多孔熔岩上的瀑布，从来没人费心把它的名字记下来",
"一个由河流注入、地表却没有任何出口的湖",
"来自四座 Ljósufjöll 火山锥、有 4000 年历史的熔岩原",
"2004 年的堤道，以及它对一座峡湾做了什么",
"冰把一整片地貌减掉了，只留下最精彩的那一块",
"封在约 110 万年前熔岩之下的海洋贝壳",
"以《Egils saga》中那位又写诗又打架的主角命名的啤酒厂",
"两名狂战士，以及他们用一次洗浴换来的那条路",
"《Eyrbyggja saga》第 11 章：山打开了，死者被迎进去",
"《Eyrbyggja saga》中的 Þrælaskriður——奴隶碎石坡",
"《Eyrbyggja saga》中的 Geirríður，被控夜间骑人",
"那三个愿望，最早的文字记载是 1955 年",
"kveldriða 的指控，最后上的是法庭，不是火刑柱",
"三到六磅的褐鳟，还有沿熔岩边缘游动的北极红点鲑",
"五万吨鲱鱼，六周之内死了两回",
"按办公时间上下班的海豹",
"以他不肯去的那个方向命名的定居者",
"1856–58 年的教堂，同类中唯一还立着的一座",
"Þórólfur 的圣山：任何人未洗净都不许看它",
"以一位萨迦诗人命名的啤酒厂",
"早在 Alþingi 之前就已开会的议事集会",
"一桩最后走进法庭而不是走上火堆的巫术指控",
"《权力的游戏》里那座箭头山",
"🍽️ 饮食",
"hákarl，以及这条鲨鱼为什么必须先好好腐熟才安全",
"🕰️ 历史",
"在一个连每条水都有名字的国家里，唯一一条始终没得到名字的瀑布",
"一个农家男孩注意到、却再没人跟进的漩涡",
"🔤 语言与地名",
"“河瀑”——冰岛语里的意思就是“我们懒得想”",
])

write("ja", [
"真東、十二キロ先——地平線上にある巨大な平頂の山です。",
"氷河がどう動くかを解き明かした田舎医者",
"斜面の上へ引っ越した農場",
"多孔質の溶岩の上を落ちる滝。誰もその名を書き留めなかった",
"川が流れ込むのに、地表にはどこにも出口がない湖",
"Ljósufjöll の四つの火砕丘から流れた、4,000年前の溶岩原",
"2004年の堤道と、それが一つのフィヨルドにもたらしたもの",
"氷が景色をまるごと削り取り、いちばん良い部分だけを残した",
"約110万年前の溶岩の下に封じ込められた海の貝",
"『Egils saga』の詩人にして喧嘩屋にちなむ醸造所",
"二人のベルセルクと、風呂を報酬に造らされた道",
"『Eyrbyggja saga』第11章——山が開き、死者が招き入れられる",
"『Eyrbyggja saga』の Þrælaskriður、奴隷の崖錐",
"『Eyrbyggja saga』の Geirríður、夜駆けの罪に問われた女",
"三つの願いごと。最初に文字になったのは1955年",
"kveldriða の告発。火刑ではなく法廷で決着がついた",
"三ポンドから六ポンドのブラウントラウトと、溶岩の縁を泳ぐイワナ",
"ニシン五万トン、六週間のあいだに二度",
"営業時間を守るアザラシたち",
"行こうとしなかった方角にちなんで名づけられた入植者",
"1856–58年の教会。同じ形で今も建つ最後の一つ",
"Þórólfur の聖なる山——身を清めずに見てはならなかった",
"サガの詩人にちなむ醸造所",
"Alþingi ができる前から開かれていた集会",
"火ではなく法廷にたどり着いた魔術の告発",
"『ゲーム・オブ・スローンズ』の矢じりの山",
"🍽️ 食べもの・飲みもの",
"hákarl——そのサメが安全になるまで、まずきちんと腐らせなければならない理由",
"🕰️ 歴史",
"あらゆる水に名のある国で、ついに名を持たなかった唯一の滝",
"農家の少年が気づき、その後誰も追いかけなかった渦",
"🔤 言語と地名",
"「川の滝」——アイスランド語で「考えるのが面倒だった」という意味",
])

write("ko", [
"정동쪽으로 십이 킬로미터 — 지평선 위 저 거대한 평정봉입니다.",
"빙하가 어떻게 움직이는지 알아낸 시골 의사",
"비탈 위로 이사 간 농장",
"구멍 숭숭한 용암 위의 폭포, 아무도 그 이름을 적어두지 않았다",
"강이 흘러들지만 지표에는 빠져나갈 곳이 하나도 없는 호수",
"Ljósufjöll의 분석구 네 개에서 나온 4,000년 된 용암대지",
"2004년의 둑길과 그것이 피오르에 한 일",
"얼음이 풍경 하나를 통째로 덜어내고 가장 좋은 부분만 남겼다",
"약 110만 년 된 용암 아래 봉인된 바다 조개껍데기",
"『Egils saga』의 시인이자 싸움꾼에게서 이름을 딴 양조장",
"베르세르크 둘, 그리고 목욕값으로 치른 그 길",
"『Eyrbyggja saga』 11장: 산이 열리고 죽은 자를 안으로 맞아들인다",
"『Eyrbyggja saga』의 Þrælaskriður — 노예의 너덜겅",
"『Eyrbyggja saga』의 Geirríður, 밤에 사람을 타고 다녔다는 혐의",
"세 가지 소원, 처음 글로 적힌 것은 1955년",
"kveldriða 혐의, 화형대가 아니라 법정에서 답했다",
"3파운드에서 6파운드짜리 갈색송어, 그리고 용암 가장자리의 곤들매기",
"청어 오만 톤, 6주 사이에 두 번",
"근무 시간을 지키는 물범들",
"가지 않겠다고 한 방향에서 이름을 얻은 정착민",
"1856–58년의 교회, 같은 방식으로 아직 서 있는 마지막 하나",
"Þórólfur의 거룩한 산: 씻지 않고는 쳐다볼 수도 없었다",
"사가 시인의 이름을 딴 양조장",
"Alþingi가 생기기 전부터 모이던 집회",
"불이 아니라 법정으로 간 마법 혐의",
"*왕좌의 게임*에 나온 화살촉 산",
"🍽️ 먹을거리와 마실거리",
"hákarl, 그리고 그 상어가 안전해지려면 왜 먼저 제대로 삭아야 하는가",
"🕰️ 역사",
"모든 물에 이름이 있는 나라에서 끝내 이름을 얻지 못한 단 하나의 폭포",
"농장 소년이 알아챘지만 아무도 확인하지 않은 소용돌이",
"🔤 언어와 지명",
"'강 폭포' — 아이슬란드어로 '우리는 굳이 애쓰지 않았다'는 뜻",
])
