#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from _tr16 import write

write("fi", [
"Katsokaa oikealle kello 1 suuntaan — harjanne hiekan yläpuolella, ja tila aivan sen päällä.",
"Tulivuori vei kirkon ja tilan marraskuussa 1660, joten se rakennettiin uudelleen ylemmäs rinteeseen ja siellä pysyttiin.",
"Sääkorvaus (jos rinne on piilossa): ”Tila on jossain tuolla sumussa — ja juuri siitä on kyse. Se pantiin ylös tarkoituksella, veden ulottumattomiin.”",
"Tila, joka nostettiin ja siirrettiin, koska **tulivuori tähtäsi siihen kerta toisensa jälkeen** — ja tulva, joka sen teki, on kirjattu lähes tunti tunnilta.",
"**Höfðabrekka** seisoi alavalla maalla tämän rinteen juurella. **3. marraskuuta 1660** Katlan tulva saavutti sen — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — ja **8.–9. marraskuuta** tuli suurin aalto: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **se vei kirkon ja suurimman osan tilan rakennuksista.**",
"Se rakennettiin uudelleen **ylös itse harjanteelle** — sinne, missä se yhä on ja minne te nyt katsotte. Tila piti nimensä ja vaihtoi osoitetta.",
"Tämä on koko tämän rannikon kaava, ja se kannattaa sanoa ääneen: täällä ei hylätä paikkaa, vaan **se siirretään rinnettä ylemmäs ja jatketaan.**",
"Kaikki tämän ja meren välillä on syy siihen — **Mýrdalssandur**, musta tasanko, joka on olemassa vain siksi, että Katla on tyhjentänyt jäätikön sen yli kerta toisensa jälkeen.",
"tila, joka rakennettiin ylemmäs vuoden 1660 tulvan jälkeen",
"jäätikkötulva, joka vei sen",
"Katsokaa eteenpäin — Vík. Tuolla alhaalla hän asui, Suður-Víkissä, vuodesta 1809.",
"Oikea vastaus liikkuvasta jäästä, kirjoitettiin vuonna 1794 maalaislääkärin kädellä ja painettiin **105 vuotta hänen kuolemansa jälkeen.**",
"Hän päätteli, miten jäätiköt liikkuvat, ratsastaessaan talolta talolle täsmälleen tällaisessa säässä — ja maailma ehti lukea sen vuonna 1945.",
"Sääkorvaus (jos jää on piilossa): ”Se on kaikki tuolla pilven alla. Hän oli ulkona täsmälleen tällaisessa säässä, hevosen selässä, muistikirja mukanaan.”",
"Vuonna **1794** maalaislääkäri seisoi jäätikkökielekkeen edessä ja päätteli jotain, mitä kukaan Euroopassa ei ollut päätellyt: **jäätiköt virtaavat.** Ne eivät ole jäätyneet paikoilleen. **Ne liikkuvat kuin jokin paksu ja puoliksi sulanut aine** — ja hän oli noin sata vuotta liian aikaisin.",
"**Sveinn Pálsson**, **1762–1840.** Hän suoritti **keväällä 1791 Kööpenhaminassa luonnontieteiden tutkinnon** — ensimmäisenä Tanskassa, joka kyseisen kokeen suoritti — ja lähti kotiin aikoen viimeistellä lääketieteellisen puolen myöhemmin. Sitä hän ei koskaan viimeistellyt. Lääkärinä hän toimi silti, koko loppuelämänsä.",
"Vuonna **1799** perustettiin uusi lääkäripiiri, joka kattoi **Árnessýslan, Rangárvallasýslan, Vestur-Skaftafellssýslan ja Vestmannasaaret.** Hän otti sen vastaan vuonna **1800**, muutti **Suður-Víkiin Mýrdalurissa vuonna 1809** — kylään, johon olemme ajamassa — ja pysyi siellä kuolemaansa asti vuonna **1840.**",
"Jäätiköt olivat hänen omaa aikaansa, eivät työtä. **Kvíárjökullilla vuonna 1794** hän katseli jään yli kaartuvia halkeamia ja kirjoitti, että se oli liikkunut *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **puoliksi sulaneena, kuin paksu sitkeästi virtaava aine.** Se on nykyvastaus: jää muovautuu oman painonsa alla ja ryömii alamäkeen.",
"Eurooppa ei koskaan päässyt lukemaan sitä. Hänen ***Ferðabók***-teoksensa ja jäätikkötutkielma ***Jöklaritið*** **jäivät käsikirjoitukseksi eikä niitä painettu ennen vuotta 1945**, kääntäjinä **Jón Eyþórsson, Pálmi Hannesson ja Steindór Steindórsson**; englanninkielinen laitos ilmestyi vuonna **2004.** Vuoteen 1945 mennessä kunnia jäätikön virtauksesta oli jo aikaa sitten mennyt muualle.",
"Ja ollaan tarkkoja siitä, minkä oppaat menevät väärin: **hän ei ollut Islannin ensimmäinen lääkäri.** Se oli hänen appensa **Bjarni Pálsson**, ensimmäinen *landlæknir*. Sveinn itse toimi hetken virkaa tekevänä *landlæknirinä*, vuosina **1803–04.**",
"piirilääkäri Víkissä, 1762–1840",
"jäätikkökieleke, jonka hän kuvasi vuonna 1794",
"hänen jäätikkötutkielmansa, painettu 1945",
"Víkin tila, jolla hän asui vuodesta 1809",
])

write("is", [
"Lítið til hægri, klukkan 1 — hálsinn upp af sandinum, með bæinn uppi á honum.",
"Eldfjallið tók kirkjuna og bæinn í nóvember 1660, svo hann var byggður aftur ofar í hlíðinni og fólk sat sem fastast.",
"Veðurleið (ef hlíðin er hulin): „Bærinn er þarna einhvers staðar í kófinu — og það er einmitt málið. Hann var settur þarna upp viljandi, þangað sem vatnið nær ekki.“",
"Bær sem var tekinn upp og fluttur af því að **eldfjallið hélt áfram að miða á hann** — og hlaupið sem gerði það er skráð nánast klukkustund fyrir klukkustund.",
"**Höfðabrekka** stóð á láglendinu neðan þessarar hlíðar. **3. nóvember 1660** náði Kötluhlaupið henni — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — og **8.–9. nóvember** kom stærsta flóðbylgjan: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **hún tók kirkjuna og bæjarhúsin að mestu.**",
"Bærinn var byggður aftur **uppi á hálsinum sjálfum** — þar sem hann stendur enn, og þangað sem þið eruð að horfa. Bærinn hélt nafninu og skipti um heimilisfang.",
"Þetta er mynstrið á allri þessari strönd og það má alveg nefna það: fólk hér yfirgefur ekki stað, það **færir hann ofar í hlíðina og heldur áfram.**",
"Allt á milli okkar og sjávar er ástæðan — **Mýrdalssandur**, svartur sandur sem er til vegna þess að Katla hefur aftur og aftur tæmt jökul yfir hann.",
"bærinn sem var endurbyggður ofar eftir hlaupið 1660",
"jökulhlaupið sem tók hann",
"Horfið fram — Vík. Þarna niðri bjó hann, á Suður-Vík, frá 1809.",
"Rétta svarið um hreyfingu íss, skrifað 1794 af héraðslækni og prentað **105 árum eftir andlát hans.**",
"Hann komst að því hvernig jöklar hreyfast á meðan hann reið milli bæja í nákvæmlega þessu veðri — og heimurinn komst í að lesa það árið 1945.",
"Veðurleið (ef ísinn er hulinn): „Þetta er allt þarna inni undir skýinu. Hann var úti í nákvæmlega svona veðri, á hesti, með vasabók.“",
"Árið **1794** stóð héraðslæknir frammi fyrir skriðjökulstungu og áttaði sig á því sem enginn í Evrópu hafði áttað sig á: **jöklar renna.** Þeir standa ekki frosnir kyrrir. **Þeir hreyfast eins og eitthvað þykkt og hálfbráðið** — og hann var um hundrað árum á undan.",
"**Sveinn Pálsson**, **1762–1840.** Hann lauk **prófi í náttúrufræði í Kaupmannahöfn vorið 1791** — fyrstur manna í Danmörku til að taka það próf — og hélt heim með þeim ásetningi að ljúka læknishlutanum síðar. Hann lauk honum aldrei. Hann stundaði lækningar samt, alla ævi.",
"Árið **1799** var stofnað nýtt læknishérað sem náði yfir **Árnessýslu, Rangárvallasýslu, Vestur-Skaftafellssýslu og Vestmannaeyjar.** Hann tók við því árið **1800**, flutti að **Suður-Vík í Mýrdal árið 1809** — þorpinu sem við erum að aka inn í — og bjó þar til dauðadags árið **1840.**",
"Jöklarnir voru hans eigin tími, ekki starfið. Við **Kvíárjökul árið 1794** horfði hann á bogadregnu rákirnar yfir ísinn og skrifaði að hann hefði runnið *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* — **hálfbráðinn, eins og þykkt efni sem rennur undan eigin þunga.** Það er nútímasvarið: ís aflagast undan eigin þunga og skríður undan halla.",
"Evrópa fékk aldrei að lesa það. ***Ferðabók*** hans og jöklaritgerðin ***Jöklaritið*** **lágu í handriti og voru ekki prentuð fyrr en 1945**, í þýðingu **Jóns Eyþórssonar, Pálma Hannessonar og Steindórs Steindórssonar**; enska útgáfan kom **2004.** Árið 1945 var heiðurinn af jöklahreyfingu löngu kominn annað.",
"Og verum nákvæm með það sem leiðsögumenn fara rangt með: **hann var ekki fyrsti læknir Íslands.** Það var tengdafaðir hans, **Bjarni Pálsson**, fyrsti *landlæknir*. Sveinn gegndi sjálfur starfi *landlæknis* um stutta hríð, **1803–04.**",
"héraðslæknirinn í Vík, 1762–1840",
"skriðjökulstungan sem hann lýsti 1794",
"jöklaritgerðin hans, prentuð 1945",
"bærinn í Vík sem hann bjó á frá 1809",
])

write("zh", [
"看右边 1 点钟方向——沙地之上的那道山脊，农场就在最顶上。",
"1660 年 11 月火山把教堂和农场一起带走了，于是他们在坡上更高处重建，继续住了下来。",
"天气备选（如果山坡被遮住）：“农场就在那片糊里的某处——而这正是重点。它是特意建到高处的，让水够不着。”",
"一座被整个搬走的农场，因为**火山一次又一次瞄准它**——而做成这件事的那场洪水，几乎是按小时记录下来的。",
"**Höfðabrekka** 原本在这道坡下的低地上。**1660 年 11 月 3 日**，卡特拉的洪水抵达——*\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"*——到 **11 月 8 日至 9 日**最大的一道浪来了：*\"sópaði burtu kirkju og bæjarhúsum að mestu\"*——**它卷走了教堂和农场的大部分房舍。**",
"他们把农场重建在**山脊之上**——它至今还在那里，也正是你们现在望着的地方。农场保住了名字，换了地址。",
"这是整条海岸线的规律，值得说破：这里的人不会放弃一个地方，他们**把它往坡上挪一挪，然后接着过日子。**",
"从这里到海之间的一切就是原因——**Mýrdalssandur**，一片黑色平原，之所以存在，只因为卡特拉一次次把一整条冰川倾泻其上。",
"1660 年洪水之后在高处重建的农场",
"把它带走的那场冰川洪水",
"看前方——维克。他就住在下面那里，在 Suður-Vík，从 1809 年起。",
"关于冰会移动的正确答案，1794 年由一位乡村医生写下，却在**他去世 105 年后**才付印。",
"他是在这样的天气里骑马挨家挨户出诊时弄明白冰川如何移动的——而世界到 1945 年才读到。",
"天气备选（如果冰被遮住）：“全都在那片云底下。他就是在这样的天气里出门的，骑着马，带着一本笔记。”",
"**1794 年**，一位乡村医生站在一条冰舌前，想通了全欧洲还没人想通的事：**冰川是流动的。**它们并非冻住不动。**它们像某种浓稠而半融的东西那样移动**——而他早了大约一百年。",
"**Sveinn Pálsson**，**1762–1840。**他在 **1791 年春天于哥本哈根取得自然科学学位**——是丹麦第一个参加那门考试的人——然后回国，打算日后再把医学那一半读完。他始终没读完。他照样行医，行了一辈子。",
"**1799 年**设立了一个新的医疗区，涵盖 **Árnessýsla、Rangárvallasýsla、Vestur-Skaftafellssýsla 和韦斯特曼纳群岛。**他于 **1800 年**上任，**1809 年迁往米达尔的 Suður-Vík**——就是我们正开进去的这个村子——一直住到 **1840 年**去世。",
"冰川是他自己的时间，不是他的差事。**1794 年在 Kvíárjökull**，他看着横过冰面的弧形裂缝，写下它曾这样移动：*\"hálfbráðinn eða sem þykkt seigfljótandi efni\"*——**半融的，像一种浓稠黏滞的物质。**这就是现代答案：冰在自身重量下变形，缓缓向下爬行。",
"欧洲始终没能读到。他的 ***Ferðabók*** 和冰川论著 ***Jöklaritið*** **一直是手稿，直到 1945 年才付印**，由 **Jón Eyþórsson、Pálmi Hannesson 和 Steindór Steindórsson** 译出；英文版则在 **2004 年**出版。到 1945 年，冰川流动的功劳早已归了别人。",
"还有一件导游常讲错的事，得说准：**他不是冰岛第一位医生。**那是他的岳父 **Bjarni Pálsson**，第一任 *landlæknir*。斯韦恩自己只是短暂代理过 *landlæknir*，在 **1803–04 年**。",
"维克的地区医生，1762–1840",
"他在 1794 年描述过的那条冰舌",
"他的冰川论著，1945 年付印",
"他从 1809 年起居住的维克农场",
])

write("ja", [
"右手、1時の方向を——砂の上に伸びる尾根、その一番上に農場があります。",
"1660年11月、火山が教会と農場をまとめて持っていきました。だから彼らは坂の上に建て直し、そのまま住み続けました。",
"悪天候用（斜面が見えないとき）「農場はあの白いもやのどこかにあります——そこがまさに肝心なところで、水が届かない高さに、わざわざ建てられたんです。」",
"まるごと持ち上げて動かされた農場です。**火山が何度もそこを狙い続けた**からで——それをやってのけた洪水は、ほぼ一時間刻みで記録に残っています。",
"**Höfðabrekka** はこの斜面の下、低い土地に建っていました。**1660年11月3日**、カトラの洪水がそこへ達します——*\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"*——そして **11月8日から9日**、最大の波が来ました：*\"sópaði burtu kirkju og bæjarhúsum að mestu\"*——**教会と農場の建物の大半を、さらっていったのです。**",
"彼らは **尾根そのものの上に** 建て直しました——今もそこにあり、まさに皆さんが見ているところです。農場は名前を守り、住所を変えました。",
"これはこの海岸線ぜんぶに通じる型で、口に出して言う値打ちがあります。ここの人は土地を捨てません。**斜面の上へずらして、そのまま続けるのです。**",
"ここから海までの一切がその理由です——**Mýrdalssandur**、カトラが氷河をまるごと何度もぶちまけたからこそ存在する黒い平原です。",
"1660年の洪水のあと高い場所に建て直された農場",
"それを持っていった氷河洪水",
"前方を——ヴィークです。彼は1809年から、あの下のSuður-Víkに住んでいました。",
"動く氷についての正しい答え。1794年に一人の田舎医者が書き留め、**彼の死から105年後**にようやく活字になりました。",
"彼はまさにこんな天気のなか、馬で農家から農家へ回りながら氷河の動き方を突き止めました——そして世界がそれを読んだのは1945年です。",
"悪天候用（氷が見えないとき）「ぜんぶあの雲の下にあります。彼はまさにこんな天気のなかを、馬に乗って、手帳を持って出ていきました。」",
"**1794年**、一人の田舎医者が氷舌の前に立ち、ヨーロッパの誰も辿り着いていなかったことを突き止めました。**氷河は流れる。**凍って止まっているのではない。**濃くて半分融けた何かのように動く**——そして彼は、およそ百年早すぎました。",
"**Sveinn Pálsson**、**1762–1840年。**彼は **1791年春、コペンハーゲンで自然科学の学位**を取りました——デンマークでその試験を受けた最初の人物です——医学の残り半分は後で仕上げるつもりで帰国しました。仕上げることはついにありませんでした。それでも彼は生涯、医者として働きます。",
"**1799年**、**Árnessýsla、Rangárvallasýsla、Vestur-Skaftafellssýsla、そしてヴェストマン諸島**を含む新しい医療区が設けられました。彼は **1800年**に着任し、**1809年にミールダールのSuður-Víkへ移り**——いま私たちが入っていく村です——**1840年**に亡くなるまでそこに住みました。",
"氷河は仕事ではなく、彼自身の時間でした。**1794年のKvíárjökull**で、彼は氷を横切る弧状の亀裂を眺め、それが *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* のように動いたと書きました——**半分融けた、粘り気のある濃い物質のように。**これが現代の答えです。氷は自らの重みで変形し、坂を這い下る。",
"ヨーロッパはついに読めませんでした。彼の ***Ferðabók*** と氷河論 ***Jöklaritið*** は **写本のまま残され、1945年まで印刷されませんでした**。訳したのは **Jón Eyþórsson、Pálmi Hannesson、Steindór Steindórsson**。英語版は **2004年**です。1945年には、氷河の流動の功績はとっくによそへ行っていました。",
"それからガイドがよく取り違える一点は正確に。**彼はアイスランド初の医師ではありません。**それは義父の **Bjarni Pálsson**、初代 *landlæknir* です。スヴェイン自身は **1803–04年**に、短いあいだ *landlæknir* 代行を務めただけです。",
"ヴィークの地区医、1762–1840",
"彼が1794年に記述した氷舌",
"1945年に印刷された彼の氷河論",
"彼が1809年から住んだヴィークの農場",
])

write("ko", [
"오른쪽 1시 방향을 보세요 — 모래 위로 솟은 능선, 그 꼭대기에 농장이 있습니다.",
"1660년 11월 화산이 교회와 농장을 함께 가져갔고, 그래서 사람들은 비탈 위쪽에 다시 지어 그대로 살았습니다.",
"악천후 대안(비탈이 가려졌을 때): \"농장은 저 안개 어딘가에 있습니다 — 그리고 바로 그게 핵심입니다. 물이 닿지 않는 높이에, 일부러 올려 지은 거니까요.\"",
"통째로 들어 옮겨진 농장입니다. **화산이 자꾸만 그 자리를 겨눴기** 때문이고 — 그 일을 해낸 홍수는 거의 시간 단위로 기록에 남아 있습니다.",
"**Höfðabrekka**는 이 비탈 아래 낮은 땅에 있었습니다. **1660년 11월 3일** 카틀라의 홍수가 그곳에 닿았고 — *\"kom fram að Höfðabrekku jöklagangur með ofurmáta miklum vatnsþunga\"* — **11월 8~9일**에 가장 큰 물결이 왔습니다: *\"sópaði burtu kirkju og bæjarhúsum að mestu\"* — **교회와 농장 건물 대부분을 쓸어 갔습니다.**",
"사람들은 **능선 위에 그대로** 다시 지었습니다 — 지금도 그 자리에 있고, 여러분이 보고 있는 곳입니다. 농장은 이름을 지키고 주소를 바꿨습니다.",
"이 해안 전체의 방식이고, 한 번 짚어둘 만합니다. 여기 사람들은 자리를 버리지 않습니다. **비탈 위로 옮기고, 하던 대로 삽니다.**",
"여기서 바다까지의 모든 것이 그 이유입니다 — **Mýrdalssandur**, 카틀라가 빙하를 통째로 몇 번이고 쏟아부었기 때문에 존재하는 검은 벌판입니다.",
"1660년 홍수 뒤 더 높은 곳에 다시 지은 농장",
"그것을 가져간 빙하 홍수",
"앞을 보세요 — 비크입니다. 그는 1809년부터 저 아래 Suður-Vík에 살았습니다.",
"움직이는 얼음에 대한 정답. 1794년 한 시골 의사가 적었고, **그가 죽은 지 105년 뒤에야** 인쇄되었습니다.",
"그는 바로 이런 날씨에 말을 타고 농가와 농가 사이를 오가며 빙하가 어떻게 움직이는지 알아냈습니다 — 그리고 세상은 1945년에야 그걸 읽었습니다.",
"악천후 대안(얼음이 가려졌을 때): \"전부 저 구름 밑에 있습니다. 그는 딱 이런 날씨에, 말을 타고, 수첩을 들고 나갔습니다.\"",
"**1794년**, 한 시골 의사가 빙하 혀 앞에 서서 유럽의 누구도 알아내지 못한 것을 알아냈습니다. **빙하는 흐른다.** 얼어붙어 멈춰 있는 게 아니다. **걸쭉하고 반쯤 녹은 무언가처럼 움직인다** — 그리고 그는 약 백 년쯤 일렀습니다.",
"**Sveinn Pálsson**, **1762–1840.** 그는 **1791년 봄 코펜하겐에서 자연과학 학위**를 받았습니다 — 덴마크에서 그 시험을 치른 첫 사람이었죠 — 그리고 의학 쪽 나머지는 나중에 마치겠다는 생각으로 귀국했습니다. 끝내 마치지 못했습니다. 그래도 평생 의사로 일했습니다.",
"**1799년** **Árnessýsla, Rangárvallasýsla, Vestur-Skaftafellssýsla, 그리고 베스트만 제도**를 아우르는 새 의료 관구가 만들어졌습니다. 그는 **1800년**에 부임했고, **1809년 미르달의 Suður-Vík으로** 옮겨 — 지금 우리가 들어가는 마을입니다 — **1840년** 세상을 뜰 때까지 거기 살았습니다.",
"빙하는 일이 아니라 그의 시간이었습니다. **1794년 Kvíárjökull**에서 그는 얼음을 가로지르는 곡선 균열들을 보고, 얼음이 *\"hálfbráðinn eða sem þykkt seigfljótandi efni\"* 처럼 움직였다고 적었습니다 — **반쯤 녹은, 걸쭉하고 끈적한 물질처럼.** 그게 현대의 답입니다. 얼음은 제 무게로 변형되며 비탈을 기어 내려갑니다.",
"유럽은 끝내 그것을 읽지 못했습니다. 그의 ***Ferðabók***와 빙하 논고 ***Jöklaritið***는 **원고로 남아 1945년에야 인쇄되었고**, **Jón Eyþórsson, Pálmi Hannesson, Steindór Steindórsson**이 옮겼습니다. 영어판은 **2004년**입니다. 1945년이면 빙하 흐름의 공은 이미 오래전에 다른 데로 넘어가 있었습니다.",
"그리고 가이드들이 자주 틀리는 대목은 정확히 해둡시다. **그는 아이슬란드 최초의 의사가 아닙니다.** 그건 장인인 **Bjarni Pálsson**, 초대 *landlæknir*였습니다. 스베인 본인은 **1803–04년**에 잠깐 *landlæknir* 대행을 맡았을 뿐입니다.",
"비크의 지역 의사, 1762–1840",
"그가 1794년에 기술한 빙하 혀",
"1945년에 인쇄된 그의 빙하 논고",
"그가 1809년부터 산 비크의 농장",
])
