#!/usr/bin/env python3
"""
Craft -> app converter for the 1.0 Golden Circle Direct script.

Craft is the manuscript. This regenerates script-1.0.js from it so the two
can never drift again.

  python3 build-script.py [--check]

Content (sub, hook, bullets, point, mic, say, tags) comes from Craft, matched
on block TITLE. Route facts (id, emoji, cue, target, weather, flag) stay as
they are in the app, because those describe where the coach is, not what is
said. Blocks in the app that Craft has never heard of are left untouched and
reported at the end.
"""
import json, re, subprocess, sys, os

CRAFT = os.path.expanduser("~/Documents/RitchWiki/Tour Scripts/1.0 Golden Circle Direct.md")
APP   = "script-1.0.js"

def parse_craft(path):
    md = open(path, encoding="utf-8").read()
    md = re.split(r'^## 🧵 Threads', md, flags=re.M)[0]
    out = {}
    for chunk in re.split(r'^> ### ', md, flags=re.M)[1:]:
        lines = chunk.split("\n")
        m = re.match(r'^(\d+\.\d+)\s+(.*)$', lines[0].strip())
        if not m:
            continue
        cid, head = m.group(1), m.group(2).strip()
        parts = re.split(r'\s+[—–]\s+', head, maxsplit=1)
        title = parts[0].strip()
        sub   = parts[1].strip() if len(parts) > 1 else ""

        rest = "\n".join(lines[1:])
        rest = re.split(r'^## ', rest, flags=re.M)[0]

        tags = re.findall(r'#\w[\w-]*', "\n".join(
            l for l in rest.split("\n") if l.lstrip("> ").startswith("🧵")))

        def grab(marker, text):
            m = re.search(r'^%s[ \t]*(.*?)(?=\n[🎣📖🎯🎤🗣️]|\Z)' % marker, text,
                          re.M | re.S)
            return m.group(1).strip() if m else ""

        hook  = grab("🎣", rest)
        point = grab("🎯", rest)
        mic   = grab("🎤", rest)
        story = grab("📖", rest)
        sayb  = grab("🗣️", rest)

        bullets = []
        for para in re.split(r'\n\s*\n', story):
            para = para.strip()
            if not para:
                continue
            if para.startswith("* "):
                bullets += [b.strip() for b in re.findall(r'^\* (.*)$', para, re.M)]
            else:
                bullets.append(re.sub(r'\s*\n\s*', ' ', para))

        say = []
        for l in re.findall(r'^\* (.*)$', sayb, re.M):
            sm = re.match(r'\s*\[(.+?)\]\s*[—–-]\s*(.+)$', l)
            if not sm:
                continue
            pron = re.sub(r'\*', '', sm.group(1)).strip()
            tail = re.sub(r'\*', '', sm.group(2)).strip()
            gm = re.match(r'^(.*?)\s*\((.+)\)\s*$', tail)
            name, gloss = (gm.group(1).strip(), gm.group(2).strip()) if gm else (tail, "")
            say.append([name, pron, gloss])

        out[title] = dict(craft_id=cid, sub=sub, hook=hook, bullets=bullets,
                          point=point, mic=mic, say=say, tags=tags)
    return out

def read_app(path):
    js = '''
      global.window={};
      eval(require("fs").readFileSync(%s,"utf8"));
      console.log(JSON.stringify(window.__SCRIPT__));
    ''' % json.dumps(path)
    return json.loads(subprocess.run(["node", "-e", js], capture_output=True,
                                     text=True, check=True).stdout)

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

def emit(script):
    L = []
    L.append("// 1.0 Golden Circle Direct — on-mic script.")
    L.append("// GENERATED by build-script.py from RitchWiki/Tour Scripts/1.0 Golden Circle Direct.md")
    L.append("// Do not hand-edit. Edit Craft, then re-run the build.")
    L.append("window.__SCRIPT__ = {")
    L.append("title: %s," % js_str(script["title"]))
    L.append("intro: [")
    for i in script.get("intro", []):
        L.append("  %s," % js_str(i))
    L.append("],")
    L.append("sections: [")
    for sec in script["sections"]:
        L.append("{title:%s, kind:%s, blocks:[" % (js_str(sec["title"]), js_str(sec["kind"])))
        for b in sec["blocks"]:
            f = ['id:%s' % js_str(b["id"])]
            if b.get("emoji"): f.append("emoji:%s" % js_str(b["emoji"]))
            f.append("title:%s" % js_str(b["title"]))
            if b.get("sub"):  f.append("sub:%s" % js_str(b["sub"]))
            if b.get("cue"):  f.append("cue:%s" % js_str(b["cue"]))
            L.append("{" + ", ".join(f) + ",")
            if b.get("target"):
                t = b["target"]
                L.append(" target:{lat:%r, lon:%r, name:%s}," % (t["lat"], t["lon"], js_str(t["name"])))
            if b.get("hook"): L.append(" hook:%s," % js_str(b["hook"]))
            if b.get("bullets"):
                L.append(" bullets:[")
                for x in b["bullets"]: L.append("  %s," % js_str(x))
                L.append(" ],")
            if b.get("heads"):
                L.append(" heads:[")
                for h in b["heads"]:
                    L.append("  [%s,[%s]]," % (js_str(h[0]), ",".join(js_str(x) for x in h[1])))
                L.append(" ],")
            if b.get("pre"):
                L.append(" pre:[")
                for pr in b["pre"]:
                    L.append("  [%s,%s]," % (js_str(pr[0]), js_str(pr[1])))
                L.append(" ],")
            if b.get("point"):   L.append(" point:%s," % js_str(b["point"]))
            if b.get("mic"):     L.append(" mic:%s," % js_str(b["mic"]))
            if b.get("weather"): L.append(" weather:%s," % js_str(b["weather"]))
            if b.get("flag"):    L.append(" flag:%s," % js_str(b["flag"]))
            if b.get("say"):
                L.append(" say:[")
                for s in b["say"]:
                    L.append("  [%s,%s,%s]," % (js_str(s[0]), js_str(s[1]), js_str(s[2] if len(s) > 2 else "")))
                L.append(" ],")
            if b.get("tags"):    L.append(" tags:[%s]," % ",".join(js_str(t) for t in b["tags"]))
            L.append("},")
        L.append("]},")
    L.append("]};")
    return "\n".join(L) + "\n"

def main():
    craft = parse_craft(CRAFT)
    script = read_app(APP)
    changed, untouched = [], []
    seen = set()
    for sec in script["sections"]:
        for b in sec["blocks"]:
            c = craft.get(b["title"])
            if not c:
                untouched.append("%s %s" % (b["id"], b["title"]))
                continue
            seen.add(b["title"])
            before = json.dumps([b.get("bullets"), b.get("say"), b.get("hook"),
                                 b.get("point"), b.get("mic"), b.get("sub")], ensure_ascii=False)
            if c["sub"]:     b["sub"] = c["sub"]
            if c["hook"]:    b["hook"] = c["hook"]
            if c["bullets"]:
                b["bullets"] = c["bullets"]
                b.pop("heads", None)
            if c["point"]:   b["point"] = c["point"]
            if c["mic"]:     b["mic"] = c["mic"]
            if c["say"]:
                # Craft wins on wording, but never throw away a gloss the app
                # already had and Craft never wrote.
                old_gloss = {x[0].lower(): (x[2] if len(x) > 2 else "")
                             for x in (b.get("say") or [])}
                b["say"] = [[n, pr, g or old_gloss.get(n.lower(), "")]
                            for n, pr, g in c["say"]]
            if c["tags"]:    b["tags"] = c["tags"]
            after = json.dumps([b.get("bullets"), b.get("say"), b.get("hook"),
                                b.get("point"), b.get("mic"), b.get("sub")], ensure_ascii=False)
            if before != after:
                changed.append("%s %s" % (b["id"], b["title"]))
    missing = [t for t in craft if t not in seen]
    print("blocks refreshed from Craft : %d" % len(changed))
    print("app-only blocks left alone  : %d  %s" % (len(untouched), "; ".join(untouched)))
    print("in Craft but not in the app : %d  %s" % (len(missing), "; ".join(missing)))
    if "--check" in sys.argv:
        return
    out = emit(script)
    open(APP, "w", encoding="utf-8").write(out)
    print("wrote %s (%d bytes)" % (APP, len(out)))

main()
