#!/usr/bin/env python3
"""
Craft document -> script JS, for either export shape.

  python3 build-any.py "5.0 South Coast" script-5.0.js

Handles both formats the Craft exports have used:
  NEW  sections "+ # 🚌 …", hooks in <callout>, say as "**Name** [PRON] — gloss"
  OLD  sections "## 🚌 …",  hooks as "🎣 …",     say as "[PRON] — Name (gloss)"
Only what the document holds goes in. Nothing invented.
"""
import json, re, os, sys

name, out = sys.argv[1], sys.argv[2]
src = os.path.expanduser("~/Documents/RitchWiki/Tour Scripts/%s.md" % name)
raw = open(src, encoding="utf-8").read()
raw = re.split(r'^\s*\+? ?#{1,2} 🧵 Threads', raw, flags=re.M)[0]

NEW = bool(re.search(r'^\+ #{1,2}\s', raw, re.M))
SEC = re.compile(r'^\+ #{1,2}\s+(.*)$') if NEW else re.compile(r'^## \s*(.*)$')
BLK = re.compile(r'^\s*> #{2,3}\s+(.*)$')
CUE = re.compile(r'^\s*> \*(.+?)\*\s*$')
SAYH= re.compile(r'^\s*(?:\+ #{2,3}\s*)?🗣️')
ITEM= re.compile(r'^\s*[-*]\s+(.*)$')
MARK= re.compile(r'^\s*(🎣|🎯|🎤|🌫️|🧵|📖)\s*(.*)$')

def clean(t):
    t = re.sub(r'\[([^\]]+)\]\(block://[^)]*\)', r'\1', t)
    t = re.sub(r'</?callout>', '', t)
    return t.strip()

sections, sec, blk = [], None, None
in_say = in_fence = False; fence=[]

def close_block():
    global blk
    if blk and sec is not None: sec["blocks"].append(blk)
    blk = None
def close_section():
    global sec
    close_block()
    if sec and sec["blocks"]: sections.append(sec)
    sec = None

for ln in raw.split("\n"):
    m = SEC.match(ln)
    if m:
        head = clean(m.group(1))
        close_section()
        if head.startswith("⚠️") or head.startswith("🧵"):
            sec = None; continue                     # safety briefing / index: not script
        kind = "stop" if head.startswith("📍") else "drive"
        sec = {"title": re.sub(r'^[📍🚌]\s*','',head).rstrip("."), "kind": kind, "blocks": []}
        in_say=False; continue
    if sec is None: continue

    if ln.strip().startswith("```"):
        if in_fence and blk: blk.setdefault("pre",[]).append(["", "\n".join(fence)]); fence=[]; in_fence=False
        else: in_fence=True
        continue
    if in_fence: fence.append(ln.rstrip()); continue

    m = BLK.match(ln)
    if m:
        close_block()
        head = re.sub(r'^\d+\.\d+\s+','', clean(m.group(1)))
        parts = re.split(r'\s+[—–]\s+', head, maxsplit=1)
        blk = {"title": parts[0].strip()}
        if len(parts)>1: blk["sub"]=parts[1].strip()
        in_say=False; continue
    if blk is None: continue

    m = CUE.match(ln)
    if m: blk["cue"]=clean(m.group(1)); continue
    if SAYH.match(ln): in_say=True; continue

    m = MARK.match(ln)
    if m:
        in_say=False
        sym, rest = m.group(1), clean(m.group(2))
        if sym=="🧵":
            tg=re.findall(r'#\w[\w-]*', rest)
            if tg: blk["tags"]=tg
        elif sym=="🎣": blk["hook"]=rest
        elif sym=="🎯": blk["point"]=rest
        elif sym=="🎤": blk["mic"]=rest
        elif sym=="🌫️": blk["weather"]=rest
        continue

    m = ITEM.match(ln)
    if m:
        text=clean(m.group(1))
        if not text: continue
        if in_say:
            a=re.match(r'^\*\*(.+?)\*\*\s*\[(.+?)\]\s*(?:[—–-]\s*(.*))?$', text)
            b=re.match(r'^\[(.+?)\]\s*[—–-]\s*(.+)$', text)
            if a:
                nm, pr, gl = a.group(1), a.group(2), (a.group(3) or "")
            elif b:
                pr, tail = b.group(1), b.group(2)
                g=re.match(r'^(.*?)\s*\((.+)\)\s*$', tail)
                nm, gl = (g.group(1), g.group(2)) if g else (tail, "")
            else: continue
            blk.setdefault("say",[]).append([re.sub(r'\*','',nm).strip(),
                                             re.sub(r'\*','',pr).strip(),
                                             re.sub(r'\*','',gl).strip()])
        else:
            blk.setdefault("bullets",[]).append(text)
        continue

    t=clean(ln)
    if t and not t.startswith(">") and not t.startswith("*****") and not in_say and "bullets" in blk:
        blk["bullets"].append(t)

close_section()
for si,s in enumerate(sections):
    for bi,b in enumerate(s["blocks"]):
        b["id"] = "%s.%d.%d" % (name.split()[0], si+1, bi+1)

def js(v): return json.dumps(v, ensure_ascii=False)
L=["// %s — generated by build-any.py from the Craft document. Do not hand-edit." % name,
   "window.__SCRIPT__ = {", "title: %s," % js(re.sub(r'^[\d.]+\s*','',name)), "sections: ["]
for s in sections:
    L.append("{title:%s, kind:%s, blocks:[" % (js(s["title"]), js(s["kind"])))
    for b in s["blocks"]:
        L.append("{"+", ".join("%s:%s"%(k,js(b[k])) for k in ("id","title","sub","cue") if k in b)+",")
        for k in ("hook","point","mic","weather"):
            if k in b: L.append(" %s:%s,"%(k,js(b[k])))
        for k,fmt in (("bullets",lambda x:"  %s,"%js(x)),):
            if k in b:
                L.append(" %s:["%k); [L.append(fmt(x)) for x in b[k]]; L.append(" ],")
        if "pre" in b:
            L.append(" pre:["); [L.append("  [%s,%s],"%(js(p[0]),js(p[1]))) for p in b["pre"]]; L.append(" ],")
        if "say" in b:
            L.append(" say:["); [L.append("  [%s,%s,%s],"%(js(x[0]),js(x[1]),js(x[2]))) for x in b["say"]]; L.append(" ],")
        if "tags" in b: L.append(" tags:[%s],"%",".join(js(t) for t in b["tags"]))
        L.append("},")
    L.append("]},")
L.append("]};")
open(out,"w",encoding="utf-8").write("\n".join(L)+"\n")
n=sum(len(s["blocks"]) for s in sections)
print("%-22s format=%s  sections %d  blocks %d  bullets %d  pronunciations %d  -> %s"
      % (name, "NEW" if NEW else "OLD", len(sections), n,
         sum(len(b.get("bullets",[])) for s in sections for b in s["blocks"]),
         sum(len(b.get("say",[])) for s in sections for b in s["blocks"]), out))
for s in sections: print("   %-34s %-6s %d" % (s["title"][:34], s["kind"], len(s["blocks"])))
