// 1.0 Golden Circle Direct — on-mic script, lifted verbatim from Craft
// document F7B2DC03-5FB5-40F8-A1E1-64156560137A on 8 Aug 2026.
//
// Structure mirrors the Craft doc exactly: drive → stop → drive → stop → stop → drive.
// `target` is what you POINT AT. `cue` is the line under the heading, verbatim.
// Blocks with target:null are story blocks — no view, tell them anywhere on that stretch.
window.__SCRIPT__ = {
title: "1.0 Golden Circle Direct",
intro: [
  "Welcome onboard your Golden Circle Direct tour, you will see its split into how we will drive the tour today.",
  "🚌 Is drive sections",
  "📍 Our stops today"
],
sections: [
{ kind:"drive", title:"BSÍ Bus Terminal → Þingvellir", blocks:[

{id:"1.0i", emoji:"🧵", title:"Three Names to Keep in Your Pocket", cue:"Leaving BSÍ — no window required.",
 target:null,
 hook:"Before we point at a single thing, pocket three names: **a painter no bishop would bless, a brewer who named his beer after a Viking, and a farm boy who won the Nobel Prize.** Their stories are about to keep crashing into each other.",
 bullets:[
  "**Kjarval** — the painter. His story opens the tour two minutes from now — and the **elf-filled altarpiece the church refused to bless** will be waiting for us in a valley up the road.",
  "**Tómas** — the brewer. He named his brewery after **Egill Skallagrímsson**, a Viking warrior-poet who could drink a hall dry — and who, as an old man, **buried a fortune in silver** in a valley we'll drive through within the hour.",
  "**Halldór** — the novelist. He grew up in **that same valley**, won Iceland's only **Nobel Prize in Literature** — and when the church binned Kjarval's rejected altarpiece, **Halldór bought it and gave it a wall in his house.** It hangs there still."],
 point:"One valley — **Mosfellsdalur, my literature valley** — ties a Viking's buried silver, a rejected painting and a Nobel medal into one twenty-minute stretch of road.",
 mic:"Keep the three names in your pocket. By the time we leave the valley, you'll know why the painting, the beer and the book all end up in the same house.",
 weather:null,
 say:[["Kjarval","KYAR-val","the painter; his story opens the tour"],
      ["Tómas Tómasson","TOH-mas TOH-mas-son","the brewer who named his beer after a Viking"],
      ["Halldór Laxness","HATL-dor LAX-ness","the farm boy who won the Nobel"],
      ["Egill Skallagrímsson","AY-til SKAHL-la-grims-son","the Viking warrior-poet connecting the brewery to the valley"],
      ["Mosfellsdalur","MOSS-fels-DAA-lur","the literature valley where the threads tie off"]],
 tags:["#art","#literature","#trade"]},

{id:"1.1", emoji:"🎨", title:"Jóhannes Sveinsson Kjarval", cue:"Look left at 9 o'clock — Klambratún Park.",
 target:{lat:64.1378705, lon:-21.9139474, name:"Kjarvalsstaðir"},
 hook:"How do you fund art school in 1900s Iceland? Your shipmates **pass a hat round a freezing cod trawler**. Not a GoFundMe — an actual hat.",
 bullets:[
  "Born **15 October 1885** at **Efri-Ey** farm in **Meðalland**, south Iceland — **9th of 13 kids** (his parents clearly had stamina). Fostered out east to **Geitavík** in **Borgarfjörður eystri**, where the fjord still calls him **\"Jói í Geitavík.\"** Too poor for paint, he drew with **calf blood, soot and wool dye** — then went to sea.",
  "Crew saw his sketches, **passed the hat**, the fishermen's union topped it up. **1911**: he tried **London** — the **Royal Academy slammed the door**. The rejection was the redirect: **Copenhagen** and the **Royal Danish Academy** (graduated **1917**).",
  "Home again he painted Iceland like no-one had — knelt over the **moss and lava three inches from his nose**, and swore he saw **elves and hidden folk** in the cracks. (In Iceland, that's not a diagnosis. That's a career.)",
  "He painted roughly **5,000 works — and gave most of them away.** The country's most valuable artist died **owning almost nothing.** That grey block in Klambratún is **Kjarvalsstaðir**, Iceland's **first purpose-built art museum** (1973); since **1995** his face is on the **2,000-króna note** — the only cod fisherman ever **promoted to legal tender.**"],
 point:"Most artists travel the world for inspiration. Kjarval found a whole country in the **dirt under his boots** — then handed it back, one canvas at a time.",
 mic:"In Iceland, the landscape looks back — and sometimes it files a complaint with the bishop.",
 weather:"If you can't make out the grey building in this weather, don't worry — Kjarval would've painted the weather instead. He usually did.",
 say:[["Jóhannes Sveinsson Kjarval","YO-han-nes SVAYN-son KYAR-val","a pioneering Icelandic painter"],
      ["Kjarvalsstaðir","KYAR-vals-STATH-ir","his museum, the grey building in the park"],
      ["Klambratún","KLAHM-bra-TOON","the Reykjavík park it stands in"],
      ["Meðalland","MEH-thal-land","the south-coast district where he was born"],
      ["Borgarfjörður eystri","BOR-gar-fyur-thur AY-stri","the east fjord where he was fostered"],
      ["Geitavík","GAY-ta-veek","the foster farm out east; the fjord still calls him \"Jói í Geitavík\""],
      ["króna","KROH-na","Iceland's currency; plural krónur"]],
 tags:["#art"]},

{id:"1.2", emoji:"🏢", title:"Ölgerðin Egill Skallagrímsson", cue:"Look right at 3 o'clock — Egils Brewery.",
 target:{lat:64.1230219, lon:-21.8019871, name:"Ölgerðin Egill Skallagrímsson"},
 hook:"How do you run Iceland's most famous brewery when beer is **illegal for 74 years**? Name it after a Viking — and brew beer that technically isn't beer.",
 bullets:[
  "Founded **17 April 1913** by **Tómas Tómasson** in two basement bedrooms of a rented Reykjavík house — at first just **1%-alcohol malt extract** — and named after **Egill Skallagrímsson**, the warrior-poet who once rhymed his way off an executioner's block (the *Höfuðlausn*, \"Head-Ransom\") and could drink a whole hall under the table. Aspirational branding.",
  "Two years later Iceland bans **all alcohol** (1915) — so Tómas sails to **Copenhagen and Germany (1915–17) to learn brewing anyway**, training up for a product his own country just outlawed. Wine creeps back in **1922**, spirits in **1935**, but **beer stays illegal until 1989**. Beer alone, because it read as **Danish** — and sipping a Danish lager while fighting Denmark for independence felt like treason.",
  "So Ölgerðin cheats: brews **Egils Pilsner kept just under the legal 2.25%** — beer that technically wasn't beer. A loophole in a glass. (The orange **Appelsín**, drowned in malt every Christmas, came later — **1955**.)",
  "The irony peaks in **1926**: after a state visit from King **Christian X**, Ölgerðin wins the right to style itself the **\"royal brewery\"** — a Danish royal blessing, in a country half-banning beer for being too Danish.",
  "Real beer returned **1 March 1989** — now **Bjórdagurinn, \"Beer Day.\"** Egils didn't fight for shelf space; they already owned it."],
 point:"Tómas didn't outrun Prohibition. He **outlived it** — 74 years on near-beer and a royal warrant.",
 mic:"Name your company after a Viking and you don't follow the rules. You wait them out.",
 weather:"If the fog's swallowed the brewery on your right, fair enough — a company that survived 74 years of Prohibition can survive one grey morning too.",
 say:[["Ölgerðin","UHL-ger-thin","Iceland's best-known brewery, founded 1913"],
      ["Egill Skallagrímsson","AY-til SKAHL-la-grims-son","the Viking warrior-poet the brewery is named after"],
      ["Appelsín","AHP-pel-seen","their orange soda, drowned in malt every Christmas"],
      ["Tómas Tómasson","TOH-mas TOH-mas-son","the founder"],
      ["Bjórdagurinn","BYOR-dah-gur-in","\"Beer Day\", 1 March, when beer became legal again"]],
 tags:["#trade"]},

{id:"1.3", emoji:"🏞️", title:"Elliðaárdalur — The Valley That Runs the City", cue:"Look right at 2 o'clock — Elliðaárdalur.",
 target:{lat:64.1106398, lon:-21.8007516, name:"Elliðaárdalur"},
 hook:"Most capitals get a grey, sad little river. Reykjavík's hands you **dinner, drinking water, electricity — and the country's first parliament.** Show-off.",
 bullets:[
  "Meet the **Elliðaá** — one of the only **capital-city rivers on Earth with a wild Atlantic salmon run**. About **2,500** shove upstream past the joggers every summer to spawn — and the city was so smitten it **bought the whole river in 1906**. (Your city buys parks. We bought a river.)",
  "The **pure tap water** your hotel keeps bragging about? Springs in this same catchment, up by the lake **Elliðavatn** — the city first drew its drinking water here in **1909**.",
  "The lights? In **1921** they dammed it for **Elliðaárstöð** — **Reykjavík's** first power station and **Iceland's second** hydro plant, switched on by King **Christian X** in person on **27 June 1921** and still running a century later.",
  "Upstream, on a low spit in **Elliðavatn** called **Þingnes**, sat the **Kjalarnesþing** — **Iceland's first assembly**, set up by **Þorsteinn Ingólfsson** (the first settler's son) before the national **Alþingi** of **930**. The old ground now lies **partly underwater**. Very Icelandic: invent democracy, then flood it. (More on parliaments shortly.)"],
 point:"Looks like a dog-walking park. It's where the capital gets **fed, watered, powered — and first learned to argue in public.**",
 mic:"Reykjavík didn't get a postcard river. It got a **Swiss Army knife.**",
 weather:"If the rain's hidden the valley on your right, just picture a green river gorge doing five jobs at once — dinner, water, power and parliament — somewhere out there in the murk.",
 say:[["Elliðaárdalur","ET-li-thow-ar-DAH-loor","the river valley on your right that feeds, waters and powers the city"],
      ["Elliðaá","ET-li-thow","the river itself, with its own wild Atlantic salmon run"],
      ["Elliðavatn","ET-li-tha-vatn","the lake upstream, where the city's drinking water springs"],
      ["Þingnes","THING-ness","the low spit in that lake where Iceland's first assembly sat"],
      ["Þorsteinn Ingólfsson","THOR-stayn ING-ohlfs-son","the first settler's son, who set that assembly up"]],
 tags:["#law","#migration","#technology"]},

{id:"1.4", emoji:"⛰️", title:"Mount Esja — A Layer Cake of Climate", cue:"Look ahead at 12 o'clock — Esja on the skyline.",
 target:{lat:64.23301, lon:-21.71115, name:"Þverfellshorn, Esja"},
 hook:"That ridge isn't a mountain — it's a **volcanic range** with **11 ice ages** stacked inside it. Reykjavík's **weather forecast, written in stone** — and unlike the app, it's never wrong.",
 bullets:[
  "**Esja** rose between **3.2 and 1.8 million years ago**, west end oldest — it's been weathering longer than humans have existed, and it isn't one mountain but a whole **volcanic range**.",
  "The stripes are climate you can read from your seat: **dark basalt** flowed in **warm, ice-free** spells and cooled in peace; **pale móberg** (tuff) is lava that picked a fight with a glacier and lost — shattered to rubble under the ice.",
  "Count the bands and you're counting cold snaps: geologists read **at least 11 separate ice ages** in there. Makes this winter look like a warm-up.",
  "True summit is **Hábunga (914 m)** — which almost nobody bothers with. The crowd-pleaser is **Þverfellshorn (~780 m)**, where a boulder called **Steinn**, about **200 m below the top**, is the official \"close enough, take the selfie\" turnaround. Touch the rock, you climbed Esja. We don't ask questions."],
 point:"Dark = warm, pale = frozen. One glance up and you've read **11 ice ages** before the lights change.",
 mic:"Reykjavíkers don't check the weather app — they check if they can still see Esja. If Esja's gone, your phone is the least of your problems.",
 weather:"If you can't see Esja on the skyline right now, congratulations — the mountain just gave you today's weather forecast, and it's a firm 'nope.'",
 say:[["Esja","ES-ya","the striped ridge on the skyline ahead; a whole volcanic range, not one mountain"],
      ["Hábunga","HOW-boong-ga","the true summit, 914 m, which almost nobody bothers with"],
      ["Þverfellshorn","THVER-fetls-horn","the peak everyone actually hikes, about 780 m"],
      ["Steinn","STAYN","the boulder 200 m below the top where hikers turn round for the selfie"],
      ["móberg","MOH-berg","the pale rock: lava that fought a glacier and got shattered under the ice"]],
 tags:["#geology"]},

{id:"1.5", emoji:"⚖️", title:"Kjalarnesþing — The Parliament Before the Parliament", cue:"At Kjalarnes, foot of Esja.",
 target:{lat:64.2421793, lon:-21.8315022, name:"Kjalarnes"},
 hook:"Iceland's world-famous parliament at Þingvellir? Not even the first. The original ran right here — set up by the founder's son. Nepotism: also a Viking value.",
 bullets:[
  "**Þorsteinn Ingólfsson** — son of **Ingólfur Arnarson**, Iceland's first settler — set up the **Kjalarnesþing** here around **900 CE**, **said to be the country's earliest assembly**, a full generation before the national Alþingi of **930**. Tradition even credits Þorsteinn with **consecrating** that later national parliament — so the founder's son didn't just build the prototype, he blessed the sequel. The þing later shuffled down to **Þingnes by Elliðavatn** (the spit we passed) and kept meeting into the **1200s**.",
  "To write proper laws, the chieftains didn't reinvent the wheel — they sent one man, **Úlfljótr**, to **Norway for three years** to study the **Gulating law** and adapt it for home. He came back with **Úlfljótur's Law**, Iceland's **first law code** — but with one radical twist the Norwegians didn't have: a parliament with **no king**. That part was all theirs."],
 point:"The big show at Þingvellir was the sequel. Kjalarnes wrote the pilot — and got no credit.",
 mic:"Kjalarnes did the homework. Þingvellir took the credit, the fame, and the tourists.",
 weather:"There's nothing to see here anyway — the first parliament left no marble and no ruins, just the fact that a thousand years ago Icelanders stood in weather exactly like this and argued the law out loud.",
 say:[["Kjalarnesþing","KYAL-ar-ness-thing","the assembly held right here, the country's earliest, around 900 CE"],
      ["Þorsteinn Ingólfsson","THOR-stayn ING-ohlfs-son","the first settler's son, who set it up"],
      ["Ingólfur Arnarson","EENG-gohl-vur AR-nar-son","his father, Iceland's first settler"],
      ["Úlfljótr","OOL-flyo-tur","the man sent to Norway for three years to bring back Iceland's first law code"],
      ["Elliðavatn","ET-li-tha-vatn","the lake the assembly later moved to"],
      ["Gulating","GOO-la-ting","the Norwegian law he studied and adapted"]],
 tags:["#law","#migration"]},

{id:"1.6", emoji:"🎵", title:"Mosfellsbær — A Town That Punches Above Its Weight", cue:"All around — Mosfellsbær.",
 target:{lat:64.1674922, lon:-21.6971313, name:"Mosfellsbær"},
 hook:"A commuter town of **~13,700** — smaller than a single Reykjavík suburb — that exported **two global music acts** at opposite ends of the volume knob.",
 bullets:[
  "**Ólafur Arnalds**, born here **1986**: **won the 2014 BAFTA TV Craft Award** for scoring ITV's *Broadchurch*, and picked up **two Grammy nominations** at the 2021 awards besides. For his *Island Songs* project (2016) he wrote **seven tracks in seven weeks at seven spots** around Iceland — one, *\"Particles,\"* with **Nanna Bryndís** of Of Monsters and Men.",
  "🎵 *Now playing — \"Particles,\" Ólafur Arnalds feat. Nanna Bryndís Hilmarsdóttir*",
  "Loud end of the dial: **Kaleo**, the blues-rock band formed here in **2012**, whose *\"Way Down We Go\"* hit **No. 1** on the US alternative chart. Their *\"Vor í Vaglaskógi\"* is a smoky cover of an Icelandic classic about a forest up north.",
  "🎵 *Now playing — \"Vor í Vaglaskógi,\" Kaleo*"],
 point:"A town this size shouldn't manage one global act. Mosfellsbær made two — whisper-quiet piano and stadium blues, from the same patch of moss.",
 mic:"Two acts, one small town, zero chill.",
 weather:"You don't need to see Mosfellsbær to hear it — a commuter town this size exported two world-famous bands, so let's just turn the music up and let the fog handle the visuals.",
 say:[["Mosfellsbær","MOS-fels-byer","the commuter town all around us, about 13,700 people"],
      ["Ólafur Arnalds","OH-la-vur AR-nalds","the composer born here in 1986, the quiet end of the volume knob"],
      ["Kaleo","KAL-ay-oh","the blues-rock band formed here in 2012, the loud end"],
      ["Nanna Bryndís","NAN-na BRIN-dees","of Of Monsters and Men; she sings on Particles"],
      ["Vor í Vaglaskógi","vor ee VAHG-la-SKOH-yi","the Kaleo track, a cover of an Icelandic classic about a forest up north"]],
 tags:["#music"]},

{id:"1.7", emoji:"🪶", title:"Mosfellsdalur — A Valley of Buried Silver and a Nobel Prize", cue:"All around — Mosfellsdalur.",
 target:{lat:64.1802753, lon:-21.6188617, name:"Mosfellsdalur"},
 hook:"Two famous residents, a thousand years apart: one **buried a fortune here and killed the witnesses**; the other won the **Nobel Prize**.",
 bullets:[
  "**The silver (from Egil's saga):** in old age the warrior-poet **Egill Skallagrímsson** — sitting on two chests of silver gifted by **King Æthelstan of England** (the same Egill the brewery back in town is named after) — slipped off during the Alþingi with the silver, a horse and two slaves. The horse came back. Egill came back. The slaves and the silver didn't — he killed them to keep the spot secret. A thousand years of treasure hunters later: score **zero**. (Saga, not survey — treat it as legend.)",
  "**The dig:** archaeologists have excavated nearby at **Hrísbrú**, where the saga says Egil's bones were later moved to the church his descendants built.",
  "**The Nobel:** born **Halldór Guðjónsson** in **1902**, raised from age three at the farm **Laxnes** just here in the valley — when he needed an author's name, **he took the farm's**. **Nobel Prize for Literature, 1955**, largely for ***Sjálfstætt fólk*** (*Independent People*).",
  "His house, **Gljúfrasteinn**, waits just up the road — that's our next stop.",
  "🎬 Down the valley sits the family riding farm at **Laxnes** — with a better screen résumé than most working actors: it supplied the **Icelandic horses for *Game of Thrones***, including the mounts **Arya Stark** and **the Hound** rode in the scenes shot at Þingvellir."],
 point:"A buried fortune no-one's ever found, and a Nobel written five minutes up the road from it.",
 mic:"One man hid his fortune. The other left his on the shelves.",
 weather:"If you can't see the valley, take comfort — a thousand years of treasure hunters couldn't find Egil's silver buried in it either, so you're in equally empty-handed company.",
 say:[["Mosfellsdalur","MOSS-fels-DAA-lur","the valley all around us: buried silver at one end, a Nobel at the other"],
      ["Halldór Laxness","HATL-dor LAX-ness","born 1902, grew up in this valley, Iceland's only Nobel laureate"],
      ["Gljúfrasteinn","GLYOO-vra-stayn","his house, now a museum with the typewriter still on the desk"],
      ["Sjálfstætt fólk","SHOWLF-stite FOLK","Independent People, the novel he won the 1955 Nobel for"],
      ["Skallagrímsson","SKAHL-la-grims-son","Egill Skallagrímsson, the warrior-poet who buried his silver here"],
      ["Hrísbrú","HREES-broo","the dig site in this valley where the saga says Egil's bones were moved"]],
 tags:["#literature","#law"]},

{id:"1.8", emoji:"🪶", title:"Gljúfrasteinn — The Poet's House", cue:"On Route 36, up the valley — Gljúfrasteinn, the white house by the river.",
 target:{lat:64.1809135, lon:-21.5818503, name:"Gljúfrasteinn"},
 hook:"That white house was built in **1945** by a novelist betting everything on staying home — **ten years later the bet paid out a Nobel Prize.**",
 bullets:[
  "**Halldór Laxness** built **Gljúfrasteinn** with his wife **Auður Sveinsdóttir** in **1945** and never really left — it was home until his death in **1998**, and it's now a museum with his **typewriter still on the desk**.",
  "**Kjarval's altarpieces, chapter one:** in **1914** he painted one for **Bakkagerði** church out east — Christ preaching from **Álfaborg**, the elf-rock, **Dyrfjöll** behind. The bishop refused to bless it — **too many elves, not enough Jesus**. It still hangs there, gloriously **unconsecrated**.",
  "**Chapter two:** his second altarpiece (*John the Baptist, Christ at his feet*) was rejected outright as **\"crude and ugly\"** — so **Halldór bought the reject and gave it a wall in this house.** One man, two altarpieces, **zero bishops convinced** — and the painter, the brewer's Viking and the novelist, the morning's three pocket names, all tie off in this one valley."],
 point:"Iceland's only Nobel came home to a quiet valley — to a house that doubles as the country's smallest gallery of rejected art.",
 mic:"A Nobel on the shelf, a rejected altarpiece on the wall — Gljúfrasteinn is where Iceland keeps the things the gatekeepers got wrong.",
 weather:"If the valley's fogged over, no matter — the man in that house spent fifty years proving you don't need to leave a rainy valley to win the Nobel Prize.",
 say:[["Gljúfrasteinn","GLYOO-vra-stayn","the poet's house: home from 1945, museum today, typewriter still on the desk"],
      ["Auður Sveinsdóttir","OY-thur SVAYNS-dot-tir","his wife, who built the house with him"],
      ["Halldór Laxness","HATL-dor LAX-ness","Iceland's only Nobel laureate, 1955"],
      ["Kjarval","KYAR-val","the painter whose rejected altarpiece hangs inside"],
      ["Bakkagerði","BAH-ka-ger-thi","the east-fjord church that still holds his 1914 elf altarpiece"],
      ["Álfaborg","OWL-va-borg","the elf-rock Christ preaches from in that painting"],
      ["Dyrfjöll","DEER-fyutl","the mountains behind the figure"]],
 tags:["#literature","#art"]},

{id:"1.9", emoji:"🚢", title:"The Norse Expansion (793–1066 CE) — Key Facts & Routes", cue:"Approaching Þingvellir.",
 target:null,
 hook:null,
 heads:[
  ["⚡ Why did the Vikings expand?",[
   "**Social** — competition among ambitious young men (polygyny, inheritance); population outgrew the land.",
   "**Economic** — silver, silk, spices, and a profitable **slave trade**.",
   "**Political** — retaliation against Christian encroachment; warfare brought status and new land."]],
  ["🗺️ Patterns",[
   "**North → South:** furs, amber, slaves, timber, walrus ivory — raided and traded out of monasteries, river towns and coastal cities from **Ireland to Morocco** (yes, Morocco — the **Nekor raid, c. 859**).",
   "**South → North:** **silver** (Islamic dirhams), **silk**, spices, weapons, luxury goods.",
   "**Reach:** sea + river networks linking the Arctic to the Mediterranean — **6,000+ miles**, Baghdad to Ireland."]],
  ["🌏 What they achieved",[
   "Trade network from the **Volga to Vínland**: Islamic silver in Scandinavia, Byzantium via the Dnieper — and the one hard proof in the west, **L'Anse aux Meadows**, Newfoundland (excavated **1960**, UNESCO **1978**), ~500 years before Columbus.",
   "Legacy: English law & language, the sagas, the world's oldest parliament (**Alþingi, 930**), the birth of **Normandy** and **Kievan Rus'**."]],
  ["⏳ How it ended (1066)",[
   "**Battle of Stamford Bridge** — Harald Hardrada's defeat closes the Viking Age.",
   "Why: political consolidation, Christianization, stronger defences, climate cooling, a shift to legal trade."]]],
 pre:[
  ["🌊 Expansion routes",
"VIKING EXPANSION ROUTES (793–1066 CE)\n\nWEST   Norway → Faroes → Iceland → Greenland → Vínland (N. America)\n                825       870       985         1000\n                Grímur    Ingólfr   Erik        Leif\n                Kamban    Arnarson  the Red     Erikson\n\nEAST   Sweden → Aldeigja → Novgorod → Kiev → Miklagarður (Constantinople)\n                753         862        882\n                Varangians  Rurik      Oleg\n\nSOUTH  Denmark → Ribe → Hedeby → Dublin → England → Normandy\n                 710    804       841       865       911\n                                           Ívarr     Gǫngu-\n                                           Boneless  Hrólfr"],
  ["🗝️ Key dates",
"🔥 793  Lindisfarne raid — traditional start of the Viking Age\n   825  Faroe Islands settlement begins\n   841  Dublin founded as a Viking longphort\n🔑 862  Rurik arrives in Novgorod\n🔥 870  Iceland settlement begins (Ingólfr Arnarson)\n🔥 878  Peace of Wedmore (Danelaw boundary set by the later Alfred–Guthrum treaty)\n   882  Oleg takes Kiev — founds Kievan Rus'\n🔑 911  Treaty of Saint-Clair-sur-Epte creates Normandy\n🔥 930  Alþingi established in Iceland\n🔥 985  Erik the Red settles Greenland\n🔥 1000 Leif Erikson reaches Vínland (N. America)\n🔑 1066 Battle of Stamford Bridge — end of the Viking Age"]],
 bullets:[], point:null, mic:null, weather:null,
 say:[["Ingólfur Arnarson","EENG-gohl-vur AR-nar-son","first settler of Iceland; the settlement begins 870"],
      ["Erik the Red","EH-rik the RED","the man who settled Greenland in 985"],
      ["Leifur Eiríksson","LAYF-ur AY-riks-son","reached Vínland in North America around the year 1000"],
      ["Haraldur harðráði","HA-rald-ur HARTH-row-thi","Harald Hardrada, whose defeat at Stamford Bridge in 1066 closed the Viking Age"],
      ["Rúrik","ROO-rik","founder of the Rurikid line in Rus'; arrived in Novgorod in 862"],
      ["Óleg","OH-leg","took Kiev in 882 and made it his capital, founding Kievan Rus'"],
      ["Hedeby","HAY-duh-by","the Danish trading town on the southern route, from about 804"],
      ["Kænugarður","KYE-nu-gar-thur","the Old Norse name for Kiev"],
      ["Mikligarður","MIK-li-gar-thur","Great City, their name for Constantinople"],
      ["Vínland","VIN-land","Wine Land, their name for North America"]],
 tags:["#warfare","#migration"]},

{id:"1.10", emoji:"🏘️", title:"Landnám — Sixty Years to Build a Country", cue:"Crossing the Settlement Era.",
 target:null,
 hook:"By tradition, in **874 CE** Iceland was all but empty. By **930**, it was full. Settled, mapped and **booted up with a national parliament** — in a single human lifetime.",
 bullets:[
  "The **Landnám** (\"Land-Taking\") is the **~60-year window** when 9,000-plus Norse, Celtic and other settlers grabbed every habitable bay and valley on the island. (**874 is the traditional date**; Ari the Wise points nearer **870**, and a nationwide ash layer — the **871 ± 2 tephra** — timestamps the whole business to the second.)",
  "The textbook source is **Landnámabók** (*The Book of Settlements*) — **400 settlers** named, their farms, feuds and home-towns mapped in detail no other Viking-age country can match.",
  "The trick: Iceland had **no locals to fight** — just a handful of Irish monks (the **Papar**) who legged it the moment longships appeared.",
  "By **930** the population (and the feuds) were big enough that the chieftains met at **Þingvellir** to launch the **Alþingi**, the world's oldest parliament still in use."],
 point:"Most countries are built over centuries by armies. Iceland was built in **two generations**, by farmers with notebooks.",
 mic:"Founding-fathers? We've got 400. We named them all. They're still in the book.",
 weather:"Nothing to point at here anyway — the whole story is that four hundred settlers filled this entire island in sixty years, and we still know all their names, fog or no fog.",
 say:[["Landnám","LAND-nowm","the Land-Taking, the sixty years when settlers filled the island"],
      ["Landnámabók","LAND-nowm-AH-bok","The Book of Settlements, which names 400 of them"],
      ["Papar","PAH-par","the Irish monks who legged it when the longships appeared"],
      ["Alþingi","AL-thing-i","the national parliament launched at Þingvellir in 930"]],
 tags:["#migration","#law","#religion"]}
]},

{ kind:"stop", title:"Þingvellir", blocks:[

{id:"1.11", emoji:"⚖️", title:"The Althing — Iceland's First Parliament", cue:"At Þingvellir — the rift valley.",
 target:{lat:64.259536, lon:-21.122538, name:"Lögberg (Law Rock)"},
 hook:"The **world's oldest parliament still in use**. Set up in **930 CE** in a literal **crack in the earth** — because the acoustics were better than anyone's farmhouse.",
 bullets:[
  "In **930 CE**, Iceland's chieftains gathered at **Þingvellir** and founded the **Alþingi** — the national assembly. They picked the spot because the **Lögberg** (\"Law Rock\") cliff wall **carried the spoken law** across the valley.",
  "For two weeks every summer the country **shut down** and came here: laws made, marriages arranged, murderers tried, beer drunk.",
  "The **Lögsögumaður** (Law-Speaker), elected for a **three-year term**, had to recite **a third of the entire legal code from memory each year** — three years to deliver the lot. Drop one clause and you could change a verdict.",
  "And there was **no king** — roughly **36 goðar** (chieftain-priests) ran the whole thing by consensus. One law, one people, zero crowns.",
  "It's run nearly continuously for **over 1,000 years**; it moved to Reykjavík in **1845** but never stopped sitting."],
 point:"No royal palace. No marble columns. Just a rock, a cliff wall, and the world's first national parliament held outdoors.",
 mic:"Britain calls itself the home of parliament. Iceland was running one **300 years before the Magna Carta** — in a hole in the ground.",
 weather:"If the mist's closed in over the rift, that's oddly perfect — the Vikings picked this spot for the cliff that carried the spoken law, so today you get the parliament by ear, not by eye.",
 say:[["Alþingi","AL-thing-i","the national assembly founded here in 930"],
      ["Lögberg","LURG-berg","the Law Rock, the cliff wall that carried the spoken law across the valley"],
      ["Lögsögumaður","LURG-soh-gu-MAH-thur","the Law-Speaker, who recited a third of the whole legal code from memory each year"],
      ["goði / goðar","GO-thi / GO-thar","the chieftain-priests, about 36 of them, who ran it by consensus"]],
 tags:["#law"]},

{id:"1.12", emoji:"🌍", title:"Þingvellir Geology — Drinking From a Dead Glacier", cue:"At Þingvellir — the rift valley.",
 target:{lat:64.258277, lon:-21.1249481, name:"Almannagjá"},
 hook:"You are standing in the **gap between North America and Eurasia** — and no, the plates do **not** meet here. They're tearing **apart**, at the speed your fingernails grow — and we have the **cleanest water on Earth** to show for it.",
 bullets:[
  "Forget the postcard version where you \"touch two continents at once.\" **Þingvellir** sits on the **Mid-Atlantic Ridge**, and what you're standing in is a **seven-kilometre-wide graben** — a strip of valley floor **sinking between two fault walls** as the plates pull apart about **2 cm a year**. The plates never touch here; the valley **is** the gap between them.",
  "The cracks have names — **Almannagjá**, the big one you walk through, is the **torn edge on the North American side**; its twin **Heiðargjá** marks the far side of the rift. The floor between them belongs to **neither continent** — it's the seam, still ripping. Filling it is **Þingvallavatn**, Iceland's largest natural lake.",
  "Clear pools like **Silfra** are meltwater that left **Langjökull** glacier **30–100 years ago**, filtered underground through porous lava — **drinkable from your cupped hand**, with underwater visibility up to **120 m**.",
  "🎬 **On screen:** Almannagjá gorge is the pass to the **Bloody Gate** in *Game of Thrones* (the gate was digitally added above the Öxarárfoss trail), and the park doubled as an otherworldly realm in ***Thor: The Dark World*** (2013)."],
 point:"Most plate boundaries sit invisible under 2 km of ocean. Here you can **walk into the gap the planet is tearing open** — and drink from it.",
 mic:"Two continents pulling apart. The cleanest drinking water on the planet running through the gap. Iceland turning a tectonic disaster into hydration.",
 weather:"Even if you can't see the gap between the two continents in this weather, you're still standing in it — and the water dripping on you left a glacier before your grandparents were born.",
 say:[["Þingvellir","THING-vet-lir","the rift valley you're standing in, sinking between the two plates"],
      ["Almannagjá","ALL-mann-a-gyow","the big crack you walk through; its west wall is the edge of the North American plate"],
      ["Heiðargjá","HAY-thar-gyow","the fault marking the far side of the rift"],
      ["Silfra","SILF-ra","the clear pool you can drink from, visibility up to 120 m"],
      ["Langjökull","LANG-yur-kutl","the glacier that water left 30 to 100 years ago"],
      ["Þingvallavatn","THING-vat-la-vatn","Iceland's largest natural lake, filling the rift floor"]],
 tags:["#geology","#film"]}
]},

{ kind:"drive", title:"Þingvellir → Haukadalur Valley", blocks:[

{id:"1.13", emoji:"🕳️", title:"The Cave People — Europe's Last Cave Family", cue:"Driving past Laugarvatnshellir.",
 target:{lat:64.2175477, lon:-20.88393, name:"Laugarvatnshellir"},
 hook:"The last family to call an Icelandic **cave** home moved out in **1922** — no electricity, no plumbing, but **their own front door** and a cow tied up next door.",
 bullets:[
  "**Laugarvatnshellir** is a pair of man-made caves hacked out of soft volcanic tuff on the **Lyngdalsheiði** heath above **Laugarvatn**.",
  "First in, **1910**: the carpenter **Indriði Guðmundsson** and **Guðrún Kolbeinsdóttir**, who ran a **coffee-bread-and-cakes tent** for passing Golden Circle travellers.",
  "Then **1918–1922**: **Jón Þorvarðsson** and **Vigdís Helgadóttir** raised **three children** in the rock. When a blizzard blocked the midwife, Jón **delivered his own daughter Ragnheiður** himself — cave dad of the century.",
  "Not medieval, either: this was **the same decade as the Model T Ford**. Reopened to visitors in **2017** — original door back in place, coffee pot and all."],
 point:"Twentieth-century Europe had jazz, cars and radio. It also had **a family raising kids in a cave**, because that's what was available.",
 mic:"Legend says a shepherd here was repeatedly **dragged out of the cave by invisible hands** — right before a blizzard that would have killed him inside. In Iceland, even the hidden folk do their own weather warnings.",
 weather:"If you can't spot the cave in the murk, that's fitting — the last family living in it raised three children through weather exactly like this, with a front door and not much else.",
 say:[["Laugarvatnshellir","LOY-gar-vatn-s-HET-lir","the pair of man-made caves families actually lived in until 1922"],
      ["Laugarvatn","LOY-gar-vatn","the place at the far end of this heath; the caves take their name from it"],
      ["Indriði Guðmundsson","IN-dri-thi GVUTH-munds-son","the carpenter who moved in first, in 1910"],
      ["Guðrún Kolbeinsdóttir","GUTH-roon KOL-bayns-dot-tir","the other 1910 tenant; together they ran a coffee-and-cakes tent for travellers"],
      ["Jón Þorvarðsson","YOHN THOR-varths-son","the father who delivered his own daughter here when a blizzard blocked the midwife"],
      ["Vigdís Helgadóttir","VIG-dees HEL-ga-dot-tir","the mother who raised three children in the rock, 1918 to 1922"],
      ["Ragnheiður","RAGN-hay-thur","the daughter born in the cave"],
      ["Lyngdalsheiði","LING-dals-HAY-thi","the heath the caves are carved into"]],
 tags:["#geology"]},

{id:"1.14", emoji:"⚖️", title:"Kristnitaka — Iceland's Conversion to Christianity", cue:"Look ahead — Þingvellir, where the decision was made.",
 target:{lat:64.2555609, lon:-21.1360746, name:"Þingvellir (behind you)"},
 hook:"Around **the year 1000**, Iceland changed its national religion **without a single sword being drawn**. No army. No martyrs. Just one pagan chieftain, one cloak, and a really long nap.",
 bullets:[
  "By **999** the country was split — Christian districts vs pagan strongholds — and Norway's King **Ólafur Tryggvason** was squeezing hard: he welcomed Christian traders into his ports, barred the pagans, and **held Icelandic hostages** as leverage. Convert, or lose the trade route you can't live without.",
  "Persuasion had gone badly: one Saxon priest, **Þangbrandur**, allegedly **fought duels and killed poets** who mocked his sermons. Not a charm offensive.",
  "By **AD 1000** (sources wobble between 999 and 1000) the **Alþingi** faced two religions, two law codes, one looming civil war — so both sides handed the verdict to one man: **Þorgeir Ljósvetningagoði**, the *pagan* Lawspeaker.",
  "He lay under his cloak **a full day and night**, then ruled: **one law, one people, one faith — Christianity** — so the young commonwealth wouldn't split in two. Private sacrifice, horse-meat and infant exposure quietly tolerated at first, then dropped. Food is food."],
 point:"Most national religions are imposed by kings or won by armies. Iceland's was decided by **a man taking a nap**.",
 mic:"Calmly, collectively, and after a really good night's sleep. That's how Iceland became Christian. Most countries weren't given the option.",
 weather:"There's nothing to see out the front anyway — the whole drama was one man lying under a cloak for a day and a night, which, in this weather, sounds like the sensible option.",
 say:[["Þorgeir Ljósvetningagoði","THOR-gayr LYOH-sveht-ning-a-go-thi","the pagan Lawspeaker who lay under his cloak a day and a night, then chose Christianity"],
      ["Þangbrandur","THANG-bran-dur","the Saxon priest who fought duels with the poets who mocked his sermons"],
      ["Ólafur Tryggvason","OH-la-vur TRIGG-va-son","Norway's king, who squeezed Iceland with port bans and hostages"]],
 tags:["#religion","#law"]},

{id:"1.15", emoji:"🌋", title:"Hekla — The Gateway to Hell", cue:"Look at 11 o'clock — Hekla, sometimes visible on a clear day.",
 target:{lat:63.9927006, lon:-19.6658171, name:"Hekla"},
 hook:"In medieval Europe, this was officially **the front door of Hell** — and the prison of **Judas Iscariot**. Iceland didn't argue. We just charged tourists.",
 bullets:[
  "**Hekla** — **1,491 m**, erupted **20+ times since the Vikings**; the **1104** blast (**VEI 5**) dropped ~**2 km³ of tephra over 55,000 km²**, one of the biggest in Iceland's record and the one that started the legend.",
  "When word of 1104 reached Europe, **Cistercian monks** ran with it — by **1180** Herbert of Clairvaux wrote that next to Hekla, Etna was \"a small furnace.\"",
  "Through the 12th–13th centuries the Church named Hekla the **literal mouth of Hell** and a prison of **Judas Iscariot**.",
  "Last erupted **February 2000** — and Hekla is so eerily quiet beforehand that seismographs picked up its run-up only about **80 minutes** before it blew.",
  "On a very, very clear day this same sightline stacks up **three more ice-capped volcanoes** toward the coast: **Tindfjallajökull**, then **Eyjafjallajökull** — of 2010 ash-cloud fame — then **Mýrdalsjökull** behind it."],
 point:"Most volcanoes get a Wikipedia entry. Hekla got a **theological one** — used to scare medieval Europe straight for 800 years.",
 mic:"Welcome to the gateway to Hell. It gives you barely **an hour and a half's notice** to send the postcards.",
 weather:"You almost never get to see Hekla anyway, so if the cloud's hiding it today, just know the medieval gateway to Hell is out there at eleven o'clock, sulking behind the weather.",
 say:[["Hekla","HEK-la","the 1,491 m volcano at eleven o'clock that medieval Europe called the gateway to Hell"],
      ["tephra","TEFF-ra","volcanic ash and fragments; Hekla dropped about 2 km³ of it in 1104"],
      ["Tindfjallajökull","TIND-fyat-la-YUR-kutl","the first of the three glaciers visible on a very clear day"],
      ["Eyjafjallajökull","AY-ya-fyat-la-YUR-kutl","the 2010 ash-cloud volcano, second in the stack"],
      ["Mýrdalsjökull","MEER-dals-YUR-kutl","the third glacier in the stack, furthest toward the coast"]],
 tags:["#geology"]},

{id:"1.16", emoji:"🛁", title:"Laugarvatn & Apavatn — Warm Water, Holy Water", cue:"Look right at 3 o'clock — Laugarvatn lake.",
 target:{lat:64.217171, lon:-20.7334229, name:"Laugarvatn"},
 hook:"What happens when you put the leaders of an entire country into the **same hot tub** to argue policy? Iceland's been finding out for **1,000 years**.",
 bullets:[
  "**Laugarvatn** (\"Pool Lake,\" ~260 people) sits on the **Hreppar block** — geothermal springs at **35–40°C** feed the lakebed, so even in winter parts of the shore run bath-warm.",
  "Its moment came around **1000 CE**: with Christianity already voted through at Þingvellir, the newly-Christian northerners and southerners rode over so they could be **baptised in the warm spring** rather than the freezing river. The spring — once **Reykjalaug** — was renamed **Vígðalaug, the \"Consecrated Pool,\"** for the event. (Westerners had their own warm spring at Krosslaug. Iceland ran baptisms by postcode.)",
  "Neighbour lake **Apavatn** (\"Marsh Lake\") is where the \"cold politics\" happened — it staged one of the dirtiest ambushes in Icelandic history. Hold that thought: the whole blood-soaked story is coming up just past the next river.",
  "Today Laugarvatn has the **Fontana** geothermal baths — the same warmth that converted the pagans, now with a bar."],
 point:"Most nations were converted at sword-point. Iceland's converts **checked the water temperature first.**",
 mic:"Other countries got baptised in freezing rivers. Iceland looked at the weather and said — no, we have a warm one.",
 weather:"If the rain's hidden Laugarvatn on your right, picture a lake so warm its shore steams in winter — the Vikings got baptised in it precisely so they wouldn't have to stand around in weather like this.",
 say:[["Laugarvatn","LOY-gar-vatn","Pool Lake on your right, warm enough at the shore to bathe in mid-winter"],
      ["Apavatn","AH-pa-vatn","Marsh Lake next door, where the 1238 ambush happened"],
      ["Vígðalaug","VEEG-tha-loyg","the Consecrated Pool, the warm spring they chose to be baptised in"],
      ["Fontana","FON-tah-na","the geothermal baths there today: same warmth, now with a bar"]],
 tags:["#religion"]},

{id:"1.17", emoji:"💙", title:"Brúará — The River That Lost Its Bridge", cue:"Crossing Brúará.",
 target:{lat:64.1345483, lon:-20.5647827, name:"Brúará"},
 hook:"A river whose name literally means **\"Bridge-River\"** — except the bridge was a **natural stone arch**, and in **1602** the church **smashed it on purpose** to keep the starving out.",
 bullets:[
  "**Brúará** (\"Bridge-River\") is a clear, spring-fed river feeding the Hvítá; its showpiece is the electric-blue waterfall **Brúarfoss**. For centuries a natural **stone arch** here was the only crossing for miles.",
  "In the famine year **1602**, the steward of **Skálholt** — the great church estate we'll visit this afternoon — with the knowledge of the bishop's wife, **Helga Jónsdóttir**, had the arch **deliberately destroyed** to stop displaced, starving people crossing to reach the estate's fertile land. Charity, Skálholt-style: demolish the bridge so the hungry can't walk over it.",
  "The river had form: back in **1433** the disgraced bishop **Jón Gerreksson** was **drowned in it in a sack** as an execution. Not a lucky river to owe a bishop money. Keep both stories in hand — we reach the estate itself this afternoon."],
 point:"A river named after a bridge — that lost the bridge because the church was tired of the poor arriving.",
 mic:"The cheapest border policy in Icelandic history: knock down the only bridge and let the river do the rest.",
 weather:"If you can't see the river we're crossing, you're missing an electric-blue waterfall called Brúarfoss — file it under 'reasons to come back on a clearer day.'",
 say:[["Brúará","BROO-au-rou","Bridge-River, the clear spring-fed river we're crossing"],
      ["Brúarfoss","BROO-ar-foss","its electric-blue waterfall"],
      ["Helga Jónsdóttir","HEL-ga YOHNS-dot-tir","the bishop's wife who knew the stone arch was being smashed in 1602"],
      ["Jón Gerreksson","YOHN GER-reks-son","the disgraced bishop drowned in this river in a sack in 1433"],
      ["Hvítá","KHVEE-tau","the glacial river this one feeds"],
      ["Skálholt","SKOWL-holt","the estate whose steward had the bridge destroyed — we visit it this afternoon"]],
 tags:["#law"]},

{id:"1.18", emoji:"⚖️", title:"The Sturlung Age — The Civil War That Ended the Republic", cue:"The 13th-century chapter most tours skip.",
 target:null,
 hook:"Iceland ran itself as a republic for **300 years**. Then **one family** decided that wasn't working — and burned the whole thing down. Literally.",
 bullets:[
  "The **Sturlungaöld** ran roughly **1220–1262** — Iceland's longest, ugliest internal war.",
  "Power had pooled in a few big clans, especially the **Sturlungar** (yes, saga-writer **Snorri Sturluson**'s family). Disputes stopped going to the Althing and started going to **swords, fires and assassinations**.",
  "**Spring 1238, at Apavatn** — the lake we just passed — **Sturla Sighvatsson** ambushed his rival **Gizur Þorvaldsson** of the Haukdælir and forced him to **swear on the Bible** to give up power and sail to Norway. Gizur had his fingers crossed.",
  "Five months later the oath came due at **Örlygsstaðir (21 August 1238)** — Gizur, teamed up with **Kolbeinn ungi**, brought **~1,700 men against ~1,000** to the **largest battle ever fought on Icelandic soil**. The northern Sturlungar were wiped out in an afternoon; Sturla's ancient family spear **Grásíða kept bending in his hands** as the tide turned, and Gizur is said to have struck the fatal blow.",
  "Snorri himself — the man who wrote down Norse mythology — was **murdered in his own cellar at Reykholt on 23 September 1241**, on the orders of the Norwegian king, by a raiding party led by **Gizur Þorvaldsson, his own former son-in-law**. His last words: ***\"Eigi skal höggva!\"*** — \"Don't strike!\" They struck.",
  "The low point: the **Burning of Flugumýri (1253)** — a wedding ambush, the hall torched with the family inside. (Often linked to *Game of Thrones'* Red Wedding — a pop claim; see verify list.)",
  "By **1262**, exhausted, the chieftains signed the **Old Covenant**, handing the country to the King of Norway. The 300-year republic was over."],
 point:"Iceland didn't lose its independence to an army. It **lost it to itself**.",
 mic:"The world's oldest parliament was killed by the same families it was built to control.",
 weather:"Nothing to point at here — this one's a story, not a view: the three-hundred-year republic that quietly tore itself apart, best told with the windows fogged and the mood suitably heavy.",
 say:[["Sturlungaöld","STURT-loongs-old","the Sturlung Age, Iceland's longest internal war, roughly 1220 to 1262"],
      ["Snorri Sturluson","SNOH-ri STURT-loo-son","the man who wrote down Norse mythology, murdered in his own cellar in 1241"],
      ["Örlygsstaðir","UR-likhs-sta-thir","the 1238 battle where the northern Sturlungar were wiped out in one afternoon"],
      ["Sturla Sighvatsson","STUR-tla SIG-vats-son","the Sturlungar chief who sprang the Apavatn ambush"],
      ["Gizur Þorvaldsson","GIS-sur THOR-valds-son","the rival who swore the oath, broke it, and won"],
      ["Grásíða","GROW-see-tha","Sturla's ancient family spear, which kept bending in his hands"],
      ["Apavatn","AH-pa-vatn","the lake where the ambush happened, two minutes back up the road"],
      ["Reykholt","RAYK-holt","Snorri's estate, where he was killed"],
      ["Flugumýri","FLU-gu-MEER-i","the 1253 wedding ambush where the hall was torched with the family inside"]],
 tags:["#law","#literature","#statehood"]},

{id:"1.19", emoji:"⚖️", title:"Haukadalur — Valley of the Hawks", cue:"At the geothermal field of Haukadalur.",
 target:{lat:64.3241337, lon:-20.2857756, name:"Haukadalur"},
 hook:"One farm in this steaming valley bred a **dynasty**: Iceland's first bishop's family, the schoolmaster who trained the nation's memory — and the man who **ended the republic**. Meet the **Haukdælir**.",
 bullets:[
  "**Haukadalur** means **\"Valley of the Hawks\"** — known now for steam, but for two centuries this was a **chieftain's seat**: the home farm of the **Haukdælir**, one of the great power families of the Icelandic Commonwealth.",
  "**Teitur Ísleifsson** — son of **Ísleifur Gissurarson, Iceland's first bishop** — settled this farm and became the **patriarch of the Haukdælir**. He ran a famous school here in the 11th century, and one of its boarders, from about **age seven**, was **Ari fróði Þorgilsson** (\"the Wise,\" c. 1067–1148) — who grew up to write **Íslendingabók**, the reason Iceland has any firm early dates at all. (The *first*-school crown belongs to **Skálholt**, down the road — we'll get there.)",
  "The family stayed at the top for two centuries — bishops, lawmen, and finally **Gizur Þorvaldsson**, the oath-breaker of Örlygsstaðir from the last stop: a **Haukdæling**, made **Iceland's first and only earl in 1258**, four years before the republic he helped bury was handed to Norway.",
  "The valley also holds the **Geysir** and **Strokkur** hot springs — the original \"geyser\" that gave the word to the world — on the **Hreppar Fault**, where superheated water reaches the surface."],
 point:"One valley, one family: the first bishop's line, the schoolroom that preserved Iceland's memory — and the earl who signed the republic away.",
 mic:"The hawks of this valley taught Iceland to read, write and pray — then one of them sold the whole country to Norway. Family legacies are complicated.",
 weather:"If the steam and fog have merged into one white wall, fitting — the family that ran this valley steered Iceland for two centuries, mostly from rooms you couldn't see into either.",
 say:[["Haukadalur","HOY-ka-dah-loor","Valley of the Hawks, the steaming valley we're in"],
      ["Teitur Ísleifsson","TAY-tur EES-layfs-son","the first bishop's son, patriarch of the Haukdælir, who ran the school at this farm"],
      ["Ari fróði","AH-ri FROH-thi","the Wise, the boy schooled here who grew up to write Iceland's first history"],
      ["Íslendingabók","EES-lend-inga-bok","the book he wrote, the reason we have any firm early dates at all"],
      ["Haukdælir","HOYK-dye-lir","the Valley-of-the-Hawks dynasty: bishops, schoolmasters and one earl"],
      ["Ísleifur Gissurarson","EES-lay-vur GIS-sur-ar-son","Iceland's first bishop, Teitur's father"],
      ["Gizur Þorvaldsson","GIS-sur THOR-valds-son","the Haukdæling who broke the oath, won the battle and became Iceland's only earl"]],
 tags:["#geology","#literature","#religion"]}
]},

{ kind:"stop", title:"Geysir", blocks:[

{id:"1.20", emoji:"⛲", title:"Geysir — The Name That Went Global", cue:"At the geothermal field — Strokkur and Geysir.",
 target:{lat:64.3126964, lon:-20.3007733, name:"Strokkur"},
 hook:"Iceland gave the world the word **\"geyser\"** — from one hot spring, in one field, on one farm.",
 bullets:[
  "The original **Geysir** is first recorded in **1294**, when earthquakes reshaped the field's springs; at its peak it threw water **70 m** up. It's mostly **dormant** now — but its reliable cousin **Strokkur** (\"the Churn\") goes **every 6–10 minutes**, **15–20 m** high (occasionally 40).",
  "Watch the **dome** bulge just before it fires: a thin layer of cooler water over near-boiling water below, pressure building until it punches through.",
  "The field sits on the **Hreppar block** — water seeps down, hits **200°C+ rock**, flashes to steam, shoots back up.",
  "**Geysir runs on earthquakes.** Born in the annals after the **1294** quakes, it roars back after every big southern shake — **1630**, **1896**, most recently **June 2000** — then dozes off again between them, sometimes for decades.",
  "Icelanders never quite accepted the naps: they used to **shovel rocks and turf in** to provoke it, and from **1963 to 1981** the official trick was **soap** — lower the surface tension and the superheated water boils over. The country literally **washed its geyser into performing**. (We've since let it sleep with dignity.)",
  "The name **Geysir** (from *geysa*, \"to gush\") first appears in writing in **1647** — and as Enlightenment scientists took an interest, the word spread to **every language on Earth**, all from this one field."],
 point:"Every other geyser on the planet is named after **this one**. Yellowstone, New Zealand, Chile — all geological cousins of one Icelandic hot spring.",
 mic:"Iceland exported the word \"geyser\" before it exported the cod.",
 weather:"Even in thick fog you'll still hear Strokkur go off and feel the ground tense up first — the one geyser that named all the others doesn't need you to see it to make its point.",
 say:[["Geysir","GAY-sir","the original hot spring that gave every language the word geyser; mostly dormant now"],
      ["Strokkur","STROK-kur","the Churn, its reliable cousin that fires every 6 to 10 minutes"]],
 tags:["#geology","#technology","#trade"]}
]},

{ kind:"stop", title:"Gullfoss", blocks:[

{id:"1.21", emoji:"💧", title:"Hvítá & Gullfoss — Meltwater and the Falls One Woman Saved", cue:"At Gullfoss.",
 target:{lat:64.3252420, lon:-20.1307390, name:"Gullfoss"},
 hook:"In **1907** an investor tried to dam this waterfall — and a farmer's daughter, **Sigríður**, fought it all the way to Reykjavík. She **lost in court** — and the falls are still here anyway.",
 bullets:[
  "**Gullfoss** (\"Golden Falls\") drops the **Hvítá** down two staircase tiers, **32 m** total, in a narrow canyon — spray throwing rainbows so consistently it looks staged.",
  "The Hvítá is **glacial meltwater** from **Langjökull**, silt-laden enough to glow gold in summer light.",
  "In **1907** an Englishman leased the falls from farmer **Tómas Tómasson** for a **hydro plant**. His daughter **Sigríður Tómasdóttir** spent her own savings on a Reykjavík lawyer — **Sveinn Björnsson**, later Iceland's **first president** — and fought for years to void the lease. The famous \"walked barefoot to Reykjavík / threatened to jump\" details are **romanticised**; she genuinely **lost in court**, but the lease then **lapsed because the developers stopped paying the rent**.",
  "Gullfoss survived, became a **nature reserve in 1979**, and Sigríður — remembered on a memorial above the falls — is now called **Iceland's first environmentalist**.",
  "🎬 **On screen:** Gullfoss shows up in *Vikings* (later seasons) and Netflix's *Lost in Space* — and it's the \"Argentina\" in the *Smallville* episode \"Zod\" (2006), where the final shot is captioned *Iguazú Falls* but is pure Gullfoss."],
 point:"The world's most famous Icelandic conservation story — lost in the courtroom, saved in the end, by a woman who never had a vote.",
 mic:"An investor showed up with engineers. A farmer's daughter showed up and lost every legal round — and the falls are still here.",
 weather:"If the spray and the mist have hidden Gullfoss, trust your ears — that roar is thirty-two metres of glacier meltwater that one farmer's daughter fought the courts to keep falling.",
 say:[["Gullfoss","GUTL-foss","Golden Falls, the two-tier 32 m drop in front of you"],
      ["Hvítá","KHVEE-tau","the glacial river that falls over it"],
      ["Sigríður Tómasdóttir","SIG-ree-thur TOH-mas-dot-tir","the farmer's daughter who fought the dam, and is now called Iceland's first environmentalist"],
      ["Sveinn Björnsson","SVAYN BYURN-son","her Reykjavík lawyer, later Iceland's first president"],
      ["Langjökull","LANG-yur-kutl","the glacier whose meltwater feeds the Hvítá"]],
 tags:["#geology","#women","#film"]}
]},

{ kind:"drive", title:"Gullfoss → BSÍ", blocks:[

{id:"1.22", emoji:"⚡", title:"Tungufljót — The Quiet Tributary & Brú Power Plant", cue:"Crossing the Tungufljót river.",
 target:{lat:64.243739, lon:-20.320552, name:"Tungufljót (Route 35 crossing)"},
 hook:"A river you've never heard of, **powering a country you have** — quietly.",
 bullets:[
  "**Tungufljót** (\"Tongue-River\") drains the highlands into the **Hvítá**, and its showpiece is **Faxi** (Vatnsleysufoss) — a broad, low **~7 m** curtain of a waterfall with a **salmon ladder** built into it.",
  "Its water now spins **Brúárvirkjun**, a small **Landsvirkjun** hydro station damming the upper river — a modern plant opened in the early **2020s**. Tiny globally; big enough to help keep this stretch of the south on the grid.",
  "Iceland runs on **~70% hydro** plus geothermal — a grid that's **~99.9% renewable**, one of the cleanest on Earth. Quiet little rivers like this are the majority behind that number."],
 point:"Iceland's most-photographed waterfall is Gullfoss. Its most useful one is **this tributary you're crossing**, doing the actual work of keeping the lights on.",
 mic:"Gullfoss gets the photos. Tungufljót gets the electricity bill paid.",
 weather:"You might not see the little river we're crossing, but it's the unglamorous hero of the story — quietly generating electricity while famous Gullfoss just poses for photos.",
 say:[["Tungufljót","TOON-gu-flyoht","Tongue-River, the quiet river we're crossing"],
      ["Faxi","FAX-i","Vatnsleysufoss, its broad 7 m curtain of a waterfall with a salmon ladder built in"],
      ["Brúárvirkjun","BROO-ar-VIRK-yun","the small hydro station its water now spins"],
      ["Hvítá","KHVEE-tau","the glacial river this one drains into"]],
 tags:["#technology"]},

{id:"1.23", emoji:"🍅", title:"Reykholt & Friðheimar — Tomatoes in the Arctic", cue:"Passing Friðheimar, Reykholt.",
 target:{lat:64.1783286, lon:-20.4476081, name:"Friðheimar"},
 hook:"We grow **tomatoes, cucumbers, peppers and strawberries** at the latitude of **Fairbanks, Alaska** — heated by hot water that **costs us almost nothing**.",
 bullets:[
  "**Reykholt** (\"smoky hill\") in **Bláskógabyggð** is the village; **Friðheimar** is its star farm — a working geothermal greenhouse complex where you can eat lunch among the vines.",
  "Inside, roughly **ten thousand tomato plants** grow under LED lights on **geothermal water** piped straight from the ground, pollinated by **imported Dutch bumblebees** — Iceland has no native pollinator strong enough for tomato flowers, so it flew in a workforce.",
  "The signature dish is **unlimited tomato soup eaten three feet from the plants that made it**. Same volcanic heat that warms Reykjavík's homes, just aimed at lunch."],
 point:"Just south of the Arctic, you shouldn't be able to grow a tomato — so Iceland grows a big share of its own tomatoes and cucumbers on volcano heat and skips the shipping.",
 mic:"At our latitude, you shouldn't be able to grow a tomato. So we built a farm on a volcano and flew in Dutch bees to run it.",
 weather:"If it's grey and gloomy out there, look for the greenhouses glowing pink through the murk — that's ten thousand tomato plants and a workforce of Dutch bumblebees ignoring the weather entirely.",
 say:[["Reykholt","RAYK-holt","smoky hill, the village we're passing"],
      ["Friðheimar","FRITH-hay-mar","its star farm, the greenhouses where you eat tomato soup among the vines"],
      ["Bláskógabyggð","BLOW-skoh-ga-byggð","the municipality Reykholt sits in"]],
 tags:["#geology","#technology"]},

{id:"1.24", emoji:"🐎", title:"Icelandic Horses — Living Viking Heritage", cue:"Look at the horses in the field.",
 target:null,
 hook:"The horse in that field is a **direct descendant of a Viking horse** — a bloodline effectively **closed for ~1,000 years**. Just don't call it a pony. That's the one hill Iceland will genuinely die on.",
 bullets:[
  "The **Icelandic horse** is small (**~132–145 cm**), shaggy, long-lived (often **30 years**), tough and frankly opinionated — and by breed convention and national insistence, **always a \"horse,\" never a pony**.",
  "No new bloodstock has arrived since roughly the year **1000**, so it's essentially a **closed, disease-naïve population** — one of the purest native breeds on Earth. Tradition says the **Alþingi** slammed the import door around **982**; the documented ban dates to **1882** — and it still stands.",
  "Most breeds have three or four gaits; the Icelandic has up to **five**, including the famous **tölt** — a four-beat running walk so smooth you could carry a full beer and not spill it. The extra gaits trace to a **single gene mutation**.",
  "Population ~**78,000** in Iceland and ~**195,000 abroad** across 30+ countries — the diaspora outnumbers the home herd two to one, and **not one of them is ever allowed back** (biosecurity enforced by MAST, the food and veterinary authority)."],
 point:"A horse breed Vikings would still recognise — kept intact for a millennium by isolation, hard winters, and a one-way export door.",
 mic:"You can take an Icelandic horse out of Iceland. You just can't bring it back. The country runs a one-way door for its own livestock.",
 weather:"If the fog's hidden the horses in the field, they don't mind — a shaggy little breed that's shrugged off a thousand Icelandic winters isn't bothered by one damp afternoon.",
 say:[["tölt","TURLT","the smooth four-beat running walk you could carry a full beer through"],
      ["Alþingi","AL-thing-i","Iceland's parliament"]],
 tags:["#law"]},

{id:"1.25", emoji:"⛪", title:"Skálholt — Bishops, Heads, and Rock Bands", cue:"At Skálholt.",
 target:{lat:64.1253127, lon:-20.524143, name:"Skálholtskirkja"},
 hook:"For **700 years**, this farm was Iceland's **capital, university and cathedral** rolled into one. Then a **1784 earthquake** ate the lot — and the country never gave it back.",
 bullets:[
  "**Skálholt** was Iceland's first **episcopal see**, founded **1056** — for 700 years the country's brain: bishops, Iceland's **first school** (Skálholtsskóli, 1056), a scriptorium and a library, all bankrolled by a guaranteed **church tithe from 1097**.",
  "It gave Iceland its **only saint** — **Þorlákur Þórhallsson**, declared holy by the Alþingi in **1198** and formally made **patron saint of Iceland by the Vatican in 1984**; his feast on 23 December still anchors the Icelandic Christmas.",
  "The **Reformation** arrived on **7 November 1550** with the beheading here of **Jón Arason** — the Catholic bishop of *Hólar*, the northern see — and two of his sons. The Lutheran takeover, sealed in blood on this lawn.",
  "A **~magnitude-7 earthquake** (South Iceland Seismic Zone) in **1784** levelled the cathedral; the Danes used it to abolish the bishopric and shift the see to a fishing village called **Reykjavík** (1796). The current church is a **1963 reconstruction** — where the blues-rock band **Kaleo** later recorded a track live, because Iceland."],
 point:"Iceland's centre of power didn't fall to an invasion. It fell to a fault line — and politics finished the job.",
 mic:"A 700-year capital, ended by a single earthquake and a Danish administrative form.",
 weather:"If the weather's swallowed the church, picture it anyway — a plain white building on a low hill that was, for seven hundred years, the entire brain of the country.",
 say:[["Skálholt","SKOWL-holt","the farm that was Iceland's capital, university and cathedral for 700 years"],
      ["Jón Arason","YOHN AR-a-son","the Catholic bishop of Hólar, beheaded here in 1550"],
      ["Þorlákur","THOR-low-kur","Iceland's only saint, whose feast on 23 December still anchors the Icelandic Christmas"]],
 tags:["#geology","#religion"]},

{id:"1.26", emoji:"🎵", title:"Grímsnes & Kerið — Red Walls, Blue Lake, Björk on a Raft", cue:"At Kerið crater.",
 target:{lat:64.0409591, lon:-20.8846110, name:"Kerið"},
 hook:"A **red volcanic crater** with a **bright blue lake** at the bottom — that **Björk once performed on**, from a **floating raft**.",
 bullets:[
  "**Kerið** is a **~6,500-year-old volcanic crater** — about **270 m long, 170 m wide and 55 m deep**: enough to swallow a **17-storey building**.",
  "The walls are **red scoria** — iron-rich basalt cinders so young the iron is **still rusting**; give it a few thousand more years and it'll blacken like its neighbours. The lake is **groundwater** (7–14 m deep) with **no inlet or outlet** — it just tracks the water table, turquoise because the water absorbs red light first against a dark floor. There's even life in it: a **2014 study found 10 kinds of zooplankton**.",
  "It sits in the **Grímsnes** volcanic field on the western rift — the northernmost of a four-crater row blown from a single eruption.",
  "The bowl's acoustics are superb, so it's hosted **concerts on a floating stage**. The famous first, in **August 1987**, drew ~**5,000 people** and was headlined by the operatic bass **Kristinn Sigmundsson**; a 21-year-old **Björk** (then in the early Sugarcubes) was on the bill too — real, but not the headliner the postcards promise."],
 point:"A crater that doubles as the world's most exclusive natural amphitheatre — built by a volcano, booked by an opera singer and a young Björk.",
 mic:"Most countries put concerts in arenas. Iceland puts them in volcanoes.",
 weather:"If the fog's filled the crater, use your imagination — bright red walls, a turquoise lake at the bottom, and once, a very young Björk singing from a raft in the middle of it.",
 say:[["Kerið","KER-ith","the red crater with the blue lake in the bottom, about 6,500 years old"],
      ["Grímsnes","GRIMS-nes","the volcanic field it sits in, on the western rift"],
      ["Björk","BYURK","on the bill here in 1987, aged 21, singing from a raft on the lake"],
      ["Kristinn Sigmundsson","KRIST-in SIG-munds-son","the operatic bass who actually headlined that 1987 concert"]],
 tags:["#geology"]},

{id:"1.27", emoji:"⚡", title:"Sog River — The River That Ran Everything", cue:"Crossing the Sog.",
 target:{lat:64.0625189, lon:-20.9914354, name:"Sog"},
 hook:"A river that's only **20 km long** — and powered **half of Iceland** for **50 years**.",
 bullets:[
  "The **Sog** flows out of **Þingvallavatn** (Iceland's biggest natural lake) and joins the Hvítá to form the Ölfusá.",
  "Short but huge in volume — **Iceland's largest clearwater (spring-fed) river**, ~**110 m³/s** of glacier-filtered, lake-clear water, perfect for hydro.",
  "Three plants — **Ljósafoss**, **Írafoss** and **Steingrímsstöð**, built **1937–1959** — a combined **~90 MW** that together ran roughly **half of Iceland's electricity** through the 1960s and 70s, until the bigger highland plants on the **Þjórsá** took over.",
  "And where did Iceland's electric age actually start? Not here — in a **carpenter's workshop in Hafnarfjörður**: on **12 December 1904**, **Jóhannes Reykdal** switched on the country's **first power station**, lighting **15 houses — the school and the Good Templars' hall among them — plus his own workshop and four street lamps**, in time for Christmas. From one carpenter's stream to all of this, in a single lifetime.",
  "Also one of Iceland's best **brown trout** rivers."],
 point:"Three small hydro plants on one short river — and they kept the country running for half a century.",
 mic:"Big rivers get the postcards. The Sog quietly ran the lights.",
 weather:"Even if the rain's hidden the Sog, remember it's only twenty kilometres long and once powered half the country — the quiet ones usually are doing the real work.",
 say:[["Sog","SOG","the 20 km river we're crossing that once powered half of Iceland"],
      ["Ljósafoss","LYOH-sa-foss","the first of its three power stations, 1937"],
      ["Írafoss","EE-ra-foss","the middle of the three power stations, 1953"],
      ["Steingrímsstöð","STAYN-grims-staeth","the last of the three, 1959"],
      ["Hvítá","KHVEE-tau","the glacial river the Sog joins"],
      ["Ölfusá","UL-vus-ow","the big drain river the two of them become"],
      ["Þjórsá","THYOR-sow","Iceland's longest river, whose bigger highland plants took over from the Sog"],
      ["Reykdal","RAYK-dal","Jóhannes Reykdal, the carpenter who switched the country on"],
      ["Hafnarfjörður","HAP-nar-fyur-thur","the town where Iceland's first power station lit up in December 1904"]],
 tags:["#geology","#law","#technology"]},

{id:"1.28", emoji:"🌊", title:"Ölfusá — The Final Drain", cue:"Look right at 1–2 o'clock — Ölfusá.",
 target:{lat:63.9359567, lon:-21.0998804, name:"Ölfusá"},
 hook:"The river ahead carries more water than any other in Iceland — and **most of it isn't even called Ölfusá**. It's **four rivers in disguise**, sharing a name only for the last 25 km.",
 bullets:[
  "The glacial **Hvítá** runs south from **Langjökull** past Gullfoss, gathering **Tungufljót** and **Brúará**.",
  "The spring-fed **Sog** drains **Þingvallavatn**. The two trunk rivers meet just above Selfoss — and from there the combined flow is the **Ölfusá**, **Iceland's biggest river by discharge** (~**423 m³/s**, draining a basin of ~**5,760 km²**).",
  "For centuries this was the ultimate obstacle: no bridge anywhere, just a ferry at **Laugardælir** paid in **cattle or cod** to reach the harbour at **Eyrarbakki**. When it flooded catastrophically in **1623**, a bishop blamed a giant river serpent — an \"ice worm.\" (It was an ice-jam flood. The serpent got the better press.)"],
 point:"Every drop of water that fell on the Golden Circle — glaciers, geysers, lakes — eventually squeezes through this one channel.",
 mic:"Four rivers. One channel. Centuries of cattle-and-cod toll. All Golden Circle water leads here.",
 weather:"If you can't see the big river off to the right, that's the Ölfusá — four rivers wearing one name, carrying more water than anything else in Iceland, somewhere out there in the grey.",
 say:[["Ölfusá","UL-vus-ow","Iceland's biggest river by discharge; four rivers under one name"],
      ["Hvítá","KHVEE-tau","the glacial half, running south from Langjökull past Gullfoss"],
      ["Sog","SOG","the spring-fed half, draining Þingvallavatn"],
      ["Laugardælir","LOY-ghar-DYE-lir","the old ferry crossing, paid in cattle or cod"],
      ["Brúará","BROO-au-rou","one of the rivers the Hvítá gathers on the way"],
      ["Langjökull","LANG-yur-kutl","the glacier the Hvítá starts from"],
      ["Tungufljót","TOON-gu-flyoht","the other river the Hvítá gathers"]],
 tags:["#geology"]},

{id:"1.29", emoji:"🏗️", title:"Selfoss — The Great Milk Collapse", cue:"Look right at 3 o'clock — Ölfusárbrú.",
 target:{lat:63.9387838, lon:-21.0047735, name:"Ölfusárbrú"},
 hook:"What's more dangerous than a world war? Apparently, **two milkmen in a very big hurry**.",
 bullets:[
  "The **1891 Ölfusárbrú** — pushed through the Alþingi by MP and banker **Tryggvi Gunnarsson** — was Iceland's **first suspension bridge**, and the town of Selfoss grew up around the crossing. No bridge, no Selfoss.",
  "In **WWII**, British troops guarded it day and night — whoever held the only crossing of Iceland's biggest river held the south.",
  "Then in **September 1944**, after 53 years, **two trucks crossed at the same time**. The eastern bearing cables couldn't take the concentrated weight, **snapped, and dropped the bridge into the river**. Both drivers survived. A replacement was built in about **five and a half months**, opening **21 December 1945** — mid-war, because the town's lifeline doesn't wait."],
 point:"The enemy that took out the Selfoss bridge wasn't an army. It was two overloaded trucks and a bridge built for lighter days.",
 mic:"The war couldn't blow this bridge up. A couple of dairy trucks did it on a Tuesday afternoon.",
 weather:"If the fog's hidden the bridge on your right, spare a thought for it — a whole world war couldn't drop it, but two overloaded milk trucks on the same afternoon absolutely did.",
 say:[["Selfoss","SEL-foss","the town that grew up around the crossing; no bridge, no Selfoss"],
      ["Ölfusárbrú","UL-vus-owr-broo","the bridge on your right, Iceland's first suspension bridge, 1891"],
      ["Tryggvi Gunnarsson","TRIG-vi GUN-nar-son","the MP and banker who pushed the bridge through the Alþingi"]],
 flag:"DATE CLASH — collapse September 1944, rebuild \"about five and a half months\", opening 21 December 1945. That is 15 months, and Dec 1945 is after VE and VJ Day, so \"mid-war\" cannot be right either. Two of those three numbers are wrong. Verify before you say it.",
 tags:["#wwii"]},

{id:"1.30", emoji:"🧭", title:"Ingólfur Arnarson — The Founder's Path", cue:"Look ahead at 12 o'clock — the Ring Road (Leið 1).",
 target:null,
 hook:"Would you move your whole family to an empty island based on **where two pieces of furniture washed up**?",
 bullets:[
  "We're on **Leið 1**, the Ring Road — only completed in **1974** for the 1,100-year settlement anniversary; before that, reaching Höfn meant hundreds of extra km on rough tracks.",
  "Per the saga, **Ingólfur Arnarson** — remembered as the **first *permanent Norse* settler** (not the first human here; Gaelic monks and a Norseman called Náttfari both beat him to it) — threw his carved **high-seat pillars** overboard and vowed to settle wherever they washed up.",
  "His slaves **Vífill and Karli** eventually found them in a bay steaming with hot springs, which he named **Reykjavík**, \"Bay of Smokes.\" (The saga's \"three-year search\" wobbles even across the old sources — treat it as story, not stopwatch.)"],
 point:"The modern Ring Road is the last chapter of that story — stitching together the coast Ingólfur started.",
 mic:"The saga begins with a man chasing two pillars. It ends with a whole nation driving the road that traces his coastline.",
 weather:"You can't see far up the road in this weather, which is fitting — Iceland's first settler picked where to live by throwing two carved pillars overboard and following where they washed up, no visibility required.",
 say:[["Leið 1","LAY-th ett","the Ring Road we're on, only completed in 1974"],
      ["Ingólfur Arnarson","EENG-gohl-vur AR-nar-son","the first permanent Norse settler, who followed his high-seat pillars ashore"],
      ["Höfn","HUFN","the south-east port that took hundreds of extra km to reach before this road"]],
 tags:["#migration"]},

{id:"1.31", emoji:"🌋", title:"Hveragerði — Quakes, Cakes and Steam", cue:"Look right at 3 o'clock — Hveragerði.",
 target:{lat:63.9975943, lon:-21.1868303, name:"Hveragerði"},
 hook:"A town of ~**2,660 people** where the ground occasionally rearranges itself — and the locals responded by **building an exhibition around the crack in their floor**.",
 bullets:[
  "Hveragerði sits on a **three-way tectonic junction** on the edge of the **Hengill volcanic system** — so geothermal that fumaroles and mud pots vent **between the houses**. On **29 May 2008** an **Mw 6.3** quake, its rupture only ~2 km away, split buildings and re-plumbed the town's hot springs.",
  "Rather than hide it, locals built the **Skjálftinn 2008** (\"The Quake\") exhibition inside the **Sunnumörk** shopping centre — right over a fissure the quake tore through the building. Stand on the crack, ride the shaking simulator.",
  "Cheap volcanic heat made it a **greenhouse town** from the 1920s (first geothermal greenhouse **1923**): tomatoes, cucumbers, flowers — and, at the horticultural college, **experimental bananas** (about a tonne a year, purely a science project — Iceland is *not* a banana republic)."],
 point:"Pizza baked by a volcano. Beer brewed with geothermal heat. A shopping mall built on an earthquake crack. Yes, all in the same town.",
 mic:"Most towns hide their disasters. Hveragerði put theirs in the lobby and charged admission.",
 weather:"If the town's lost in the murk, look for the steam rising between the houses — Hveragerði sits on a tectonic junction so lively it built a museum around the crack an earthquake tore through the mall.",
 say:[["Hveragerði","KVE-ra-ger-dhi","the greenhouse town on your right, with steam venting between the houses"],
      ["Skjálftinn","SKYALF-tin","The Quake, the exhibition built over the crack the 2008 earthquake tore"],
      ["Sunnumörk","SUN-nu-murk","the shopping centre that fissure runs through"]],
 tags:["#geology"]},

{id:"1.32", emoji:"🏢", title:"Hellisheiðarvirkjun — The Dragon's Breath", cue:"Look right at 2 o'clock — Hellisheiði geothermal plant.",
 target:{lat:64.0365423, lon:-21.3976306, name:"Hellisheiðarvirkjun"},
 hook:"In most countries, a volcano is a disaster plan. In Iceland, it's the **light switch**.",
 bullets:[
  "We're on the **Hengill volcanic system**, a rare **plate-boundary triple junction on dry land**. Water goes down, returns at nearly **300°C**, and spins turbines — the white plumes are **steam**, not smoke. Built up in stages 2006–2011 to **303 MW**, it's **Iceland's largest geothermal power station**.",
  "After the electricity, the leftover hot water pipes off to heat **more than half of the capital region** — nothing wasted.",
  "Via **CarbFix**, CO₂ is dissolved in water and pumped into hot basalt, where **~95% turns to solid rock within about two years** (Matter et al., 2016). Next door, **Climeworks' Mammoth** plant (2024) sucks CO₂ straight from the air — up to **36,000 tonnes a year** — for the same rock treatment."],
 point:"While the world debates carbon capture, Iceland dissolves the problem in water, files it under \"rocks,\" and moves on.",
 mic:"Your shower in Reykjavík tonight was heated by the same volcano that's currently filing CO₂ as gravel under your feet.",
 weather:"If the fog's merged with the steam plumes on your right, you honestly can't tell where the weather ends and the power station begins — and either way, that's what's heating your shower tonight.",
 say:[["Hellisheiðarvirkjun","HEL-li-shay-thar-VIRK-yun","Iceland's largest geothermal power station, the steam plumes on your right"],
      ["Hengill","HEN-gitl","the volcanic system underneath it, a plate-boundary triple junction on dry land"],
      ["Hellisheiði","HEL-lis-HAY-thi","the heath and pass the plant is named after"]],
 tags:["#technology","#geology"]},

{id:"1.33", emoji:"⛰️", title:"Kristnitökuhraun — The Decision Rock", cue:"Look left at 9 o'clock — Kristnitökuhraun, the Christianity Lava.",
 target:{lat:64.0153893, lon:-21.493378, name:"Kristnitökuhraun"},
 hook:"Can a volcano vote? Around **the year 1000**, one sort of did. One chieftain out-thought it with a single question.",
 bullets:[
  "Remember **Þorgeir under his cloak** at Þingvellir this morning? Same assembly, same knife-edge year — two faiths, two law codes, one looming civil war. This lava field is where that story grew teeth.",
  "At peak tension a messenger reported **lava flowing on Hellisheiði**. Pagans cried \"the gods are angry!\"",
  "Chieftain **Snorri Goði** pointed at the ancient lava underfoot: *\"What were the gods angry about when this rock was made?\"* Silence — and Iceland chose Christianity to keep **one law** for the whole island. *(Kristni saga)*",
  "**And here's the thing — look left: the dark field out your window IS that lava.** It's the fresh top of the three-flow **Svínahraun** stack, radiocarbon-dated to around **1000 CE**, so it **inherited its name** from the conversion it coincided with. Fitting footnote: today the **CarbFix** project uses this very basalt to turn CO₂ into stone — the rock that once \"proved\" divine anger now mops up industrial emissions."],
 point:"A whole country's religion settled by a single, calm geology question.",
 mic:"The pagans claimed a volcano was voting. Snorri pointed out the ballot box was older than the religion.",
 weather:"Even hidden in mist, the point of this lava field survives — a thousand years ago one chieftain looked at rock exactly this old and asked which gods were angry when it formed, and that settled a whole nation's religion.",
 say:[["Kristnitökuhraun","KRIST-ni-tuh-ku-HROYN","the Christianity Lava on your left, named for the conversion it coincided with"],
      ["Svínahraun","SVEE-na-hroyn","the three-flow lava stack it sits on top of"],
      ["Snorri Goði","SNOH-ri GO-thi","the chieftain who asked what the gods were angry about when the old rock was made"],
      ["Hellisheiði","HEL-lis-HAY-thi","the heath where the lava was reported flowing"],
      ["Þorgeir Ljósvetningagoði","THOR-gayr LYOH-sveht-ning-a-go-thi","the Lawspeaker whose cloak-nap verdict this lava is named for"]],
 tags:["#geology","#literature","#religion"]},

{id:"1.34", emoji:"⛰️", title:"Rauðhólar — The Mars Impostors", cue:"Look right at 3 o'clock — Rauðhólar.",
 target:{lat:64.0942147, lon:-21.7552248, name:"Rauðhólar"},
 hook:"A line of perfect little volcanoes — and **not one of them is real**. NASA can't get enough.",
 bullets:[
  "These are **pseudocraters** (Icelandic *gervigígar*) — properly, **rootless cones**: no magma pipe, no roots. Fake volcanoes.",
  "**~5,000 years ago** lava from the **Leiti** shield volcano rolled over the **Heiðmörk** wetland; trapped water flashed to steam and, in a **phreatomagmatic** blast, **punched back out** through the molten lava — frozen mid-explosion in red scoria (iron oxide — rust).",
  "Originally ~**80 cones**. Because a rootless cone only forms where lava met water, geologists read Iceland's as a template for **Mars** — the rootless cones of **Athabasca Valles** are cited as evidence of buried water on the Red Planet.",
  "Then, practically, the British army mined the field for gravel to build **Reykjavík airport** in WWII; digging continued for years. Protected in **1974**.",
  "One full-circle glance before the city: behind the cones lies **Elliðavatn** — and on a low spit in it, **Þingnes**, the **second home of the Kjalarnesþing**, the regional assembly you met this morning. It kept meeting there into the **1200s** — so you're leaving the Golden Circle past the country's original parliament grounds.",
  "And the electricity story closes here too: the **Elliðaár** valley below held **Reykjavík's first power station (1921)** — seventeen years after **Reykdal's carpentry-shop plant** lit the nation's first bulbs in Hafnarfjörður. From a workshop stream to a volcano filing CO₂ as gravel: one century of Icelandic power, and you've just driven the whole arc."],
 point:"Two armies and one city carved up Iceland's Mars lab and paved it into a runway.",
 mic:"Eighty cones. One Mars classroom. Half of it now under your runway.",
 weather:"If you can't see the little red hills on your right, don't feel cheated — they're fake volcanoes with no roots, so convincing that NASA studies them to understand Mars, all wasted on today's fog.",
 say:[["Rauðhólar","ROY-thoh-lar","the little red cones on your right; fake volcanoes with no roots"],
      ["Leitahraun","LAY-ta-HROYN","the lava from the Leiti shield volcano that rolled over the wetland"],
      ["Heiðmörk","HAY-thmurk","the wetland it rolled over, whose trapped water blew the cones out"],
      ["Elliðavatn","ET-li-tha-vatn","the lake behind the cones, holding the old assembly ground"],
      ["Þingnes","THING-ness","the low spit where the Kjalarnesþing kept meeting into the 1200s"],
      ["Kjalarnesþing","KYAL-ar-ness-thing","the regional assembly from this morning, in its second home"],
      ["Elliðaár","ET-li-thow-ar","the river valley holding Reykjavík's first power station"],
      ["Reykdal","RAYK-dal","the Hafnarfjörður carpenter whose 1904 plant lit the nation's first bulbs"]],
 tags:["#geology"]}
]}
]};
