// A - St Thomas More Special (geology, bullets) — generated by build-any.py from the Craft document. Do not hand-edit.
window.__SCRIPT__ = {
title: "A - St Thomas More Special (geology, bullets)",
sections: [
{title:"7. GULLFOSS → GEYSIR", kind:"drive", blocks:[
{id:"A.1.1", title:"⏸️ MID-DAY REMINDER", cue:"\"That question from this morning — destroyer and provider, same force? We're about to see the clearest example of it yet.\"",
},
]},
],
};
