// D - St Thomas More Special (bullet edition) — generated by build-any.py from the Craft document. Do not hand-edit.
window.__SCRIPT__ = {
title: "D - St Thomas More Special (bullet edition)",
sections: [
],
};
